### ISSUE TITLE
🐛 FromSeed() does not set value from seeded object property

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [AutoFixture/AutoFixture#1457] opened 2024-05-08 14:38 UTC
### Describe the Bug
FromSeed() does not set value from seeded object property
I'm using AutoFixture 5.0.0-preview0011

### Scenario
```csharp
public class FromSeedTests
{
    private class Foo { public string StrVal { get; set; } }

    [Fact]
    public void TestFromSeed()
    {
        // Arrange
        var fixture = new Fixture();
        var fooSeed = new Foo() {StrVal = "FromSeed",};

        fixture.Customize<Foo>(c => c.FromSeed(seed => new Foo() {StrVal = seed.StrVal}));

        // Act
        var fooFromSeed = fixture.Create<Foo>(fooSeed);

        // Assert
        Assert.Equal("FromSeed", fooFromSeed.StrVal);
    }
}
```
produces this assertion error
```
Xunit.Sdk.EqualException
Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "FromSeed"
Actual:   "StrVal117cc748-74ef-4dd2-827d-0acfcac60f6"···
           ↑ (pos 0)
   at XunitTestProject_01.FromSeedTests.TestFromSeed() ...
```

### Expected Behavior
I've expected the value from seeded value to be copied to created object but it wasn't

Maybe I have wrong assumptions about how __fromSeed()__ works but if that is the case ,it is because I couldn't find good documentation with examples how to correctly use it and why my example fails. (same applies to __fromFactory()__)
I've tried links like: 
- https://autofixture.github.io/docs/quick-start/
- https://github.com/AutoFixture/AutoFixture/wiki
- .. all Mark's Seeman blog posts with AutoFixture tag

Can you please add documentation about how to use fromSeed/FromFactory (and also probably how **not** to use it ?)

**Comment by aivascu** [comment] 2024-05-08 19:01
Hi @grzegorz-wolszczak,
The behavior you are observing is not a bug. `FromSeed` works similar to the `FromFactory` method in the builder API.
It will provide a way to create an object instance from a seed but will not prevent default behavior.
I your case since the `Foo.StrVal` has a public setter the value in that property will be overridden by the initialization of auto-properties. To avoid it you could either use 'OmitAutoProperties()` or explicitly omit that specific member `.Without(x => x.StrVal)`.

Here's a working example:
```cs
[Fact]
public void TestFromSeed()
{
    // Arrange
    var fixture = new Fixture();
    var fooSeed = new Foo() { StrVal = "FromSeed", };

    fixture.Customize<Foo>(c => c
        .FromSeed(seed => new Foo() { StrVal = seed.StrVal })
        .Without(x => x.StrVal));

    // Act
    var fooFromSeed = fixture.Create<Foo>(fooSeed);

    // Assert
    Assert.Equal("FromSeed", fooFromSeed.StrVal);
}
```

Regarding the documentation. I know there isn't much to go on.
At the moment the project priorities lie in other areas. If you wish to help you could raise a PR in the [documentation project](https://github.com/AutoFixture/AutoFixture.github.io).

**Comment by aivascu** [comment] 2024-05-08 19:09
closing the issue.
if in doubt about other features, please open a question in the [discussions](https://github.com/AutoFixture/AutoFixture/discussions/categories/q-a).

**Closed by aivascu** 2024-05-08 19:09 UTC
Labels: bug

**Comment by Kralizek** [comment] 2024-05-08 19:15
I have been often puzzled by the from seed method because its behavior feels unnatural or, at the very least, conflicting with the intent declared by the name.

In my opinion, an object constructed from a seed should be equivalent to the seed unless explicitly customized otherwise.

I'd consider changing the method so that OmitAutoProperties is automatically included

It will then be responsibility of the user to specify With(property) to force the generation of a new value for the specific property.

**Comment by aivascu** [comment] 2024-05-08 19:38
@Kralizek I can only assume, but I think the intention was to allow creation of related values. Using the original object as a prototype.
For example objects with the same foreign key, people with the same last name, etc.
To create a new object you'd create a specimen builder that would handle a seeded request for a specific type.
Then in that handler you'd specify how the value is created and return it. No other alterations would be made to that object, since the resulting object was created.
It's the fact that @grzegorz-wolszczak used the builder API that forced the other properties to be filled in.

For example:

```cs
[Fact]
public void TestFromSeed()
{
    // Arrange
    var fixture = new Fixture();
    fixture.Customizations.Add(new SeededFooBuilder());
    var fooSeed = new Foo { StrVal = "FromSeed" };

    // Act
    var fooFromSeed = fixture.Create<Foo>(fooSeed);

    // Assert
    Assert.Equal(fooSeed.StrVal, fooFromSeed.StrVal);
    Assert.Null(fooFromSeed.OtherStrVal);
}

public class Foo
{
    public string StrVal { get; set; }
    public string OtherStrVal { get; set; }
}

public class SeededFooBuilder : ISpecimenBuilder
{
    public object Create(object request, ISpecimenContext context)
    {
        if (request is not SeededRequest seededRequest)
        {
            return new NoSpecimen();
        }

        if (seededRequest.Seed is not Foo foo)
        {
            return new NoSpecimen();
        }

        return new Foo { StrVal = foo.StrVal };
    }
}
```
