### ISSUE TITLE
Generic extension method over parameter constrained to an interface fails as nested expression

### ISSUE THREAD

**Issue by hambroz** [AutoFixture/AutoFixture#970] opened 2018-01-19 16:20 UTC
Hi there,

First let me thank you for all the amazing work you do, AutoFixture is simply great!:)

Now to the problem. I will try to describe it as thorough as possible. Please ask more questions if needed.

I will start with the fact that the issue I will describe was not present in v3.50.2 and emerged in v4. As I use some customisations more often in the setup phase, I decided to create an extension method which does them for me. The extension method looks like this:

```c#
public static class AutofacExtensions
{
    public static IPostprocessComposer<T> WithUnknownData<T>(this IPostprocessComposer<T> composer, ISpecimenContext context, int dataLength) where T : IUnknownRecord
        => composer.With(rec => rec.UnknownData, context.CreateMany<byte>(dataLength).ToHexString());
}
```

As my "records" (e.g. classes I customise using this extension methods) do not have a specific base class containing the UnknownData property, I decided to go for an interface describing "unknown records" and being defined as this:

```c#
public interface IUnknownRecord
{
    string UnknownData { get; set; }
}
```

The extension method is then called in a lambda function like this:

```c#
(builder, context) => builder.WithUnknownData(context, 12)
```

instead of this:

```c#
(builder, context) => builder.With(rec => rec.UnknownData, context.CreateMany<byte>(12).ToHexString())
```

where `rec` is the "record" class. And here comes the issue. With v4, you implemented the fail-fast checking for nested expressions. I have quickly checked the code of the `VerifyIsNonNestedWritableMemberExpression` method and it seems that to support my scenario it would need to do another call to `TryUnwrapConversion` somewhere in the `if` block on line 29 in the same manner as on line 12/13 in the `GetWritableMember`. I don't want to guess if this can or cannot have some hidden side effects, but as of now this seems as a solution to me.

This only happens if the extension method is type-constrained to an interface. If I try to do the same with the base class (and customise a different property contained in the base class), there is no conversion, thus no `UnaryExpression`.

If anything, let me know!

All the best, Jan

**Comment by zvirja** [comment] 2018-01-20 10:51
Thanks a lot for such a detailed description and the initial investigation you already did! You are absolutely right in your findings and the root cause of the issue was identified correctly. I don't think there should be some issues with the suggested fix, as the failing code is a pure sanity check.

The scenario you provided is absolutely valid, given that if validation is omitted, the rest part of the AutoFixture works perfectly fine.
I'll push a fix via PR soon and will release a new version after the fix is merged. 

Thanks again for the detailed report!

**Closed** 2018-01-20 19:28 UTC
Labels: bug
