### ISSUE TITLE
AutoMoq a concrete dependency

### ISSUE THREAD

**Issue by Euan-McVie** [AutoFixture/AutoFixture#1202] opened 2020-10-01 12:43 UTC
Hi,

I am trying to use a Moq of a concrete dependency.

```cs
[Theory, AutoMoqData]
public async Task Can_register_a_single_service_successfully(
    [Frozen] Mock<IdentityServerOptions> identityServerOptions,
    ServiceDiscoveryUsingIdentityServer sut
)
{...}
```

This throws an error where AutoFixture is trying to create a real instance of `IdentityServerOptions` to inject into my `sut` instead of using the frozen mock.
If I remove the sut and manually create passing in the `identityServerOptions.Object` then it all works, so my working theory is that autofixture/automoq is not picking up that the frozen moq can satisfy the dependency and so tries to create a new instance.

I also tried `Frozen(Matching.DirectBaseType)` as the proxy generated by moq inherits from the requested value, but still no luck.

Is there any way around this as I can't change `IdentityServerOptions` as it's 3rd party and have more variables to inject to my sut, which makes the workaround a bit messy when I only need to access the one from my example.

Thanks
Euan

**Comment by Kralizek** [comment] 2020-10-01 13:30
Just freeze `IdentityServerOptions` and use `Mock.Get`.

Check this page of the booklet I wrote for my developers: https://docs.educationsmediagroup.com/unit-testing-csharp/autofixture/combining-autofixture-with-nunit-and-moq

**Comment by Euan-McVie** [comment] 2020-10-01 13:36
Unfortunately that doesn't work as `IdentityServerOptions` is not an abstract class nor an interface and so the `AutoMoqCustomization` doesn't generate a Moq for it.

For completeness the attribute is:
```cs
public AutoMoqDataAttribute()
    : base(() => new Fixture().Customize(new AutoMoqCustomization()))
{ }
```

**Comment by Kralizek** [comment] 2020-10-01 13:41
Then I don't understand your issue. Why do you need to use Moq at all?

**Comment by Euan-McVie** [comment] 2020-10-01 13:47
`IdentityServerOptions` is not my class, and can't be instantiated easily from a unit test so I need to Mock it to pass into my `sut`. The mocking all works great, but it appears AutoFixture/AutoMoq doesn't pick up on the fact that a Mock<IdentityServerOptions> can be used in place of a `IdentityServerOptions` dependency.

**Comment by Euan-McVie** [comment] 2020-10-01 13:53
Current workaround:
```cs
[Theory, AutoMoqData]
public async Task Can_register_a_single_service_successfully(
    [Frozen] ILogger<ServiceDiscoveryUsingIdentityServer> logger,
    [Frozen] IAuditor<ServiceDiscoveryUsingIdentityServer> auditor,
    [Frozen] Mock<IdentityServerOptions> identityServerOptions,
    ... the other dependencies.
)
{
   //Arrange
   var sut= new ServiceDiscoveryUsingIdentityServer(logger, auditor, identityServerOptions, identityService, authorizationService, grpcService);
}
```
This makes it a little messy to have to list all the dependencies when I'm only usually needing the identityServerOptions mock for most of the test cases.

**Comment by aivascu** [comment] 2020-11-30 22:05
@Euan-McVie sorry for a late reply.
I hope to shed some light into the issue you're experiencing and possibly a workaround that might help you.

While I was not around when AutoMoq was developed, I believe this behavior was intended.

As you probably know AutoMoq can inject mocks two ways either as a mock and as the mocked type.
The current implementation mocks by default any interface or abstract type, given no other customizations have already intercepted the request for the same type. Which is why the auto mocking occurs for requests that have passed through the entire resolution pipeline, right before throwing an exception because the request couldn't be satisfied.

If we were to move the auto-mocking customizations closer to the beginning of the pipeline, then most types would be resolved as mocks. This is not desirable because then the types dependencies would be `null` or the mock would throw on creation because some guard clauses prevented the creation of the object in an invalid state.

Now it might seem logical that the `[Frozen]` mocks would be properly resolved, but due to the internal design we cannot tell which types are frozen/injected because the conditions under which the same instance would always be returned are too complex.
A context request for a mock of a mocked type would almost always yield a value, since almost any type can be mocked and we wouldn't know whether the request was satisfied by a frozen value.

As a workaround for your issue I suggest customizing the concrete type to be created from a mock.

```csharp
public class CustomCustomization : ICustomization
{
    public void Customize(IFixture fixture)
    {
        fixture.Customize<IdentityServerOptions>(
            x => x.FromFactory<IFixture>(
                f => f.Create<Mock<IdentityServerOptions>>().Object));
    }
}
```
Since you would have already frozen the mock in your test parameter when you'd requested it in your SUT you would receive the same instance.
```csharp
[Theory, AutoMoqData]
public async Task Can_register_a_single_service_successfully(
    [Frozen] Mock<IdentityServerOptions> identityServerOptions,
    ServiceDiscoveryUsingIdentityServer sut)
```
I will leave this issue open for a little while, in case you have more questions on this topic.

**Comment by Euan-McVie** [comment] 2020-12-01 14:07
Thanks for the response.

Would it work if I created a custom `MockAttribute : CustomizeAttribute` so that I could do something like:
```cs
[Theory, AutoMoqData]
public async Task Can_register_a_single_service_successfully(
    [Frozen, Mock(typeof(IdentityServerOptions))] IdentityServerOptions identityServerOptions,
    [Frozen] ILogger<ServiceDiscoveryUsingIdentityServer> logger,
    [Frozen] IAuditor<ServiceDiscoveryUsingIdentityServer> auditor,
    ServiceDiscoveryUsingIdentityServer sut)
```

This would be preferred as then the standard `AutoMoqData` attribute works to generate the other parameters so I can control the specific mocks of concrete objects per test rather than having lots of `AutoMoqWithMockXYZ` style attributes for other scenarios.

Would this possibly work (not had a chance to test yet myself), or would it not combine properly with the `Frozen` and underlying `AutoMoqData`? 
```cs
public AutoMoqDataAttribute()
    : base(() => new Fixture().Customize(new AutoMoqCustomization()))
{ }
```
Thanks

**Comment by aivascu** [comment] 2020-12-01 17:20
@Euan-McVie I suppose you could indeed do that. Here's a naive implementation of a customization that could achieve parameter specific mocking

```csharp
public class MockCustomization : ICustomization
{
    public MockCustomization(ParameterInfo parameterInfo)
    {
        ParameterInfo = parameterInfo;
    }

    public ParameterInfo ParameterInfo { get; }

    public void Customize(IFixture fixture)
    {
        var mockedType = ParameterInfo.ParameterType.GetGenericArguments()[0];
        fixture.Customizations.Add(new MockRelay(new ExactTypeSpecification(mockedType)));
    }
}
```
You could then define an attribute that uses it
```csharp
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class MockAttribute : Attribute, IParameterCustomizationSource
{
    public ICustomization GetCustomization(ParameterInfo parameter)
    {
        return new MockCustomization(parameter);
    }
}
```
and finally the test would look something like this
```csharp
[Theory]
[AutoData]
public void DependencyShouldBeSameAsMockedObject(
    [Frozen][Mock] Mock<DependencyClass> dependencyMock,
    SystemUnderTest sut)
{
    Assert.Same(dependencyMock.Object, sut.Dependency);
}
```

**Comment by aivascu** [comment] 2020-12-02 21:51
Closing the issue.
The question seems to have been answered.

**Closed by aivascu** 2020-12-02 21:51 UTC
Labels: question

**Comment by Euan-McVie** [comment] 2020-12-03 09:02
Looks great thanks.

**Comment by Kralizek** [comment] 2020-12-03 09:06
@aivascu do you think the types above could be incorporated in the AutoMoq library?

They seem generic and general purpose enough to deserve the honour.

**Comment by aivascu** [comment] 2020-12-07 14:26
@Kralizek yes it might be useful to have it in the AutoMoq lib.
 I'll add an issue to the backlog, with a proposal for this feature.

**Comment by Euan-McVie** [comment] 2020-12-08 13:50
Finally had a chance to test it and it works great.
I made a minor improvement (I know its still not robust enough for all uses) so that you can still request the concrete object instead of the Mock wrapper.
```cs
public void Customize(IFixture fixture)
{
    Type? mockedType = (typeof(IMock<object>).IsAssignableFrom(ParameterInfo.ParameterType))
        ? ParameterInfo.ParameterType.GetGenericArguments()[0]
        : ParameterInfo.ParameterType;
    fixture.Customizations.Add(new MockRelay(new ExactTypeSpecification(mockedType)));
}
```
Allows
```cs
[Theory]
[AutoData]
public void DependencyShouldBeSameAsMockedObject(
    [Frozen][Mock] DependencyClass dependencyMock,
    SystemUnderTest sut)
{
    Assert.Same(dependencyMock.Object, sut.Dependency);
}
```

**Comment by Kralizek** [comment] 2021-05-14 08:28
> @Kralizek yes it might be useful to have it in the AutoMoq lib.
> I'll add an issue to the backlog, with a proposal for this feature.

Since I recently stumbled upon this very issue, do you mind me putting forward a PR to implement the `MockAttribute` as you specified?

@aivascu

**Comment by aivascu** [comment] 2021-05-14 11:56
@Kralizek yes please do if you have implemented it. AFAIR when I attempted to implemented it wasn't as trivial as the implementation from above. Lets move the discussion to #1269 .
