### ISSUE TITLE
Generator doesn't create enum combinations

### ISSUE THREAD

**Issue by DavidUser** [AutoFixture/AutoFixture#1237] opened 2021-02-22 21:20 UTC
I'm using a fixture and testing cases expecting that different enum configurations are being tested but on reality, if the enums have the same size the combinations aren't tested.

A combinatory test should be:
```
aEnum  bEnum

0        0
0        1
0        2
1        0
1        1
1        2
...

```

But current behaviour is like bellow

```
aEnum  bEnum

1        1
2        2
0        0
1        1
2        2
0        0
1        1
...

```

## Output:
```
Create
{"aEnum":0,"bEnum":0,"id":51}

Generator
{"aEnum":1,"bEnum":1,"id":106}
{"aEnum":2,"bEnum":2,"id":180}
{"aEnum":0,"bEnum":0,"id":200}
{"aEnum":1,"bEnum":1,"id":35}
{"aEnum":2,"bEnum":2,"id":223}
{"aEnum":0,"bEnum":0,"id":189}
{"aEnum":1,"bEnum":1,"id":92}
{"aEnum":2,"bEnum":2,"id":140}
{"aEnum":0,"bEnum":0,"id":26}
{"aEnum":1,"bEnum":1,"id":251}
```

## Testing code
```
using System;
using AutoFixture;
using System.Linq;

namespace console
{
  enum A { a0, a1, a2 };
  enum B { b0, b1, b2 };

  class Foo {
    public A aEnum { get; set; }
    public B bEnum { get; set; }
    public int id { get; set; }
  }

  class Program
  {
    static void Main(string[] args)
    {

      var fixture = new Fixture();
      var create = fixture.Create<Foo>();

      Console.WriteLine("Create");
      print(create);
      Console.WriteLine();

      var generator = fixture.Create<Generator<Foo>>().Take(10);

      Console.WriteLine("Generator");
      foreach (var entry in generator)
      {
        print(entry);
      }
      Console.WriteLine();
    }

    private static void print<T>(T obj) {
      Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(obj));
    }
  }
}
```

**Comment by Ergamon** [comment] 2021-02-28 22:40
Believe it or not, this is the expected behavior.

The standard enum generator in AutoFixture returns enum values in sequence. So because your 2 enums have the same amount of values, they are always in sync.

You can create a random generator like this:

```
  public class RandomEnumSequenceGenerator : ISpecimenBuilder
  {
    private static readonly Random Random = new Random();

    public object Create(object request, ISpecimenContext context)
    {
      var type = request as Type;
      
      if (type?.IsEnum != true)
      {
        return new NoSpecimen();
      }

      var values = Enum.GetValues(type);
      var index = Random.Next(values.Length);
      return values.GetValue(index);
    }
  }
```

To make sure your implementation is used, you have to place the customization **before** the others.

So change your code like this:

```
...
      var fixture = new Fixture();
      fixture.Customizations.Insert(0, new RandomEnumSequenceGenerator());

      var create = fixture.Create<Foo>();
...
```

**Comment by aivascu** [comment] 2021-03-01 10:15
@DavidUser this behavior is indeed intended by design, as mentioned by @Ergamon.

If you really need to test all possible enum combinations I would recommend making it an explicit test scenario, where you could provide the test data using a data source such as inline attribute, method or separate class even (most testing frameworks support it), depending on the complexity of your scenario.

Closing the issue. Feel free to reopen if there are any more questions.

**Closed by aivascu** 2021-03-01 10:15 UTC
