### ISSUE TITLE
ArgumentException after upgrading from Moq 4.10.1 to 4.11 (and later)

### ISSUE THREAD

**Issue by pmiossec** [AutoFixture/AutoFixture#1161] opened 2020-01-21 15:47 UTC
I have a mock that is created, using `Autofixture.Moq` nuget package, with:

```csharp
var fixture = new Fixture();
fixture.Customize(new AutoMoqCustomization());
var myMock = fixture.Create<IMyInterface>()
```

That was working with Moq 4.10.1 but no more with Moq 4.11 and later.

But now, when calling a method on this mock, I've got the exception:

```csharp
System.ArgumentException
Argument types do not match
   at ConstantExpression System.Linq.Expressions.Expression.Constant(object value, Type type)
   at void Moq.Mock.AddInnerMockSetup(Invocation invocation, object returnValue)
   at void Moq.Return.Handle(Invocation invocation, Mock mock)
   at void Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Dictionary<int, CategoryResult[]> Castle.Proxies.ICoreServiceProxy.GetCategoryResultsFormattedForEntity(out long cacheRevision, Nullable<int> idAnalysis, int entityID, List<AttributeAndFormat> attributes, int beginPeriod, int endPeriod, Periodicity periodicitySelected, bool ignoreOutOfBounds, TalianceToken talianceToken, Nullable<int> idSnapshot)
```

Could you give me a clue from where the problem could come from?

I'm not really sure if it's a `AutoFixture.Moq` problem (and need an update with newer `moq` releases) or a `Moq` regression... So including @stakx in the report.

**Comment by snekbaev** [comment] 2020-03-25 03:38
Hi, just tried AutoMoq for the first time, seems like it doesn't play well with the latest Moq v4.13.1, getting
```
System.IO.FileLoadException: Could not load file or assembly 'Moq, Version=4.1.1308.2120, Culture=neutral, PublicKeyToken=69f491c39445e920' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Any plans to update? :)
Thank you!

**Comment by stakx** [comment] 2020-03-25 06:54
I cannot reproduce this problem.

First, there is no AutoFixture.Moq package &mdash; there is AutoFixture.AutoMoq and AutoFixtureMoq... which one did you use? (I am assuming the former, but asking just in case.)

Second, what does your `IMyService` and your mock method call look like?

**Comment by jzabroski** [comment] 2020-12-13 19:05
@stakx You can close this - it's stale.  We use AutoFixture.AutoMoq 4.14.0 and it works great.

If I had to guess, the issue was with some regressions in Mock.VerifyAll() introduced between 4.10 and 4.13

**Comment by aivascu** [comment] 2020-12-14 07:19
@jzabroski I have reproduced the setup from the original post with the latest AutoFixture and I could not reproduce the failure.
I used a .NET Framework unit test project with the following dependencies.

```cs
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoFixture" version="4.14.0" targetFramework="net472" />
  <package id="AutoFixture.AutoMoq" version="4.14.0" targetFramework="net472" />
  <package id="Castle.Core" version="4.4.0" targetFramework="net472" />
  <package id="Fare" version="2.1.1" targetFramework="net472" />
  <package id="Moq" version="4.11.0" targetFramework="net472" />
  <package id="MSTest.TestAdapter" version="2.1.1" targetFramework="net472" />
  <package id="MSTest.TestFramework" version="2.1.1" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" targetFramework="net472" />
</packages>
```
The following test fails.
```cs
[TestMethod]
public void MockCreationShouldFail()
{
    var fixture = new Fixture();
    fixture.Customize(new AutoMoqCustomization());
    Action act = () => fixture.Create<IMyInterface>();

    Assert.ThrowsException<Exception>(act);
}

public interface IMyInterface
{
}
```

Closing this issue.
If anyone finds a reproducible example, feel free to reopen the issue.

**Closed by aivascu** 2020-12-14 07:19 UTC

**Comment by pmiossec** [comment] 2021-02-09 15:50
Giving another quick try to update from "4.10.1" to "4.16.0" and `AutoFixture.AutoMoq` from "4.11.0" to"4.15.0" and I still have the problem.

I have a better stacktrace:

```
System.ArgumentException
Argument types do not match
   at ConstantExpression System.Linq.Expressions.Expression.Constant(object value, Type type)
   at InvocationShape Moq.InvocationShape.CreateFrom(Invocation invocation) in C:/projects/moq4/src/Moq/InvocationShape.cs:line 31
   at void Moq.Behaviors.ReturnBaseOrDefaultValue.Execute(Invocation invocation) in C:/projects/moq4/src/Moq/Behaviors/ReturnBaseOrDefaultValue.cs:line 82
   at void Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:/projects/moq4/src/Moq/Interception/Mock.cs:line 34
   at void Moq.CastleProxyFactory+Interceptor.Intercept(IInvocation underlying) in C:/projects/moq4/src/Moq/ProxyFactories/CastleProxyFactory.cs:line 107
   at void Castle.DynamicProxy.AbstractInvocation.Proceed()
```

I don't have a good understanding because that's a big dirty test (not unit at all!!) but the behavior change is still there.
I have to figure it out what is the real problem but that will require more investigation...

**Comment by aivascu** [comment] 2021-02-10 17:29
@pmiossec I don't see anything in the stacktrace related to AutoFixture. Which version of `Moq` do you have installed?

**Comment by stakx** [comment] 2021-02-10 23:37
@pmiossec, I'm happy to take a look whether there is a problem inside Moq, but I can only help if I have a complete, minimal, executable repro code available that can be executed without having to guess missing code fragment. Without repro code, there's not much that can be done.

**Comment by pmiossec** [comment] 2021-02-11 12:35
Hi all,

There is definitely a behavior change in  v4.11 of Moq.
I raised this issue to have a beginning of understanding of if it was our test code that has a problem or a real bug in Moq (probably less likely).

>I'm happy to take a look whether there is a problem inside Moq, but I can only help if I have a complete, minimal, executable repro code available that can be executed without having to guess missing code fragment. Without repro code, there's not much that can be done.

Unfortunately, the tests that now failed are not very good tests (too big and not really well written) and trying to have a repro case would be too much time consuming for me without a real idea if I will be able to achieve it.

Replacing the mock created by AutoMoq by a mock created using `new Mock<IMyInterface>()` is solving the issue and allowed us to update Moq dependency.

As a consequence, I will stop my investigation there.

 I really thank you all for having spend some time on this issue!
