### ISSUE TITLE
AutoFixture xUnit2 Properties accessed prematurely

### ISSUE THREAD

**Issue by Sylapse** [AutoFixture/AutoFixture#593] opened 2016-04-05 06:59 UTC
When creating an instance with AutoData, I find that all the public properties of the TestClass have their get methods called before execution enters the body of the test and before the chance to setup the behaviour of mocks.

Is this normal? I am having to use a fixture directly to create test objects where these premature get calls affect the outcome.

    [Theory, AutoData]
    public void Sample_test(TestClass testClass ) {

    }

**Comment by ploeh** [comment] 2016-04-07 19:58
Thank you for reporting this. That's surprising, and I currently haven't investigated enough to offer an explanation. However, here's a more explicit repro:

```C#
public class TestClass
{
    public bool WasRead { get; private set; }

    private string theText;
    public string TheText
    {
        get
        {
            this.WasRead = true;
            return this.theText;
        }
        set
        {
            this.theText = value;
        }
    }
}

public class Tests
{
    [Theory, AutoData]
    public void Repro(TestClass testClass, string expected)
    {
        Assert.False(testClass.WasRead); // Fails

        testClass.TheText = expected;
        var actual = testClass.TheText;

        Assert.Equal(expected, actual);
        Assert.True(testClass.WasRead);
    }

    [Fact]
    public void NoReproWithoutAutoData()
    {
        var fixture = new Fixture();
        var testClass = fixture.Create<TestClass>();
        var expected = fixture.Create<string>();

        Assert.False(testClass.WasRead);

        testClass.TheText = expected;
        var actual = testClass.TheText;

        Assert.Equal(expected, actual);
        Assert.True(testClass.WasRead);
    }
}
```

The `Repro` test fails at the line with the `// Fails` comment, whereas the `NoReproWithoutAutoData` test passes. This strengthens the hypothesis that the behaviour is associated explicitly with `[AutoData]`.

FWIW, here's my package list for the above repro:

```
PM> Get-Package

Id                                  Versions
--                                  --------
AutoFixture                         {3.43.0}
AutoFixture.Xunit2                  {3.43.0}
xunit                               {2.1.0} 
xunit.abstractions                  {2.0.0} 
xunit.assert                        {2.1.0} 
xunit.core                          {2.1.0} 
xunit.extensibility.core            {2.1.0} 
xunit.extensibility.execution       {2.1.0} 
```

**Comment by ploeh** [comment] 2016-04-07 20:11
The `[AutoData]` attribute is a slim Adapter over `Fixture`, and as the above `NoReproWithoutAutoData` test demonstrates, the problem isn't immediately reproducible with a basic `Fixture`.

This suggests that the issue is either in `[AutoData]` or somewhere in the _xUnit.net 2_ framework. I can't identify any piece of code in [the `[AutoData]` attribute source code](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net2/AutoDataAttribute.cs) that would cause a read of a public property, so I wonder if the _xUnit.net 2_ framework might perform a read - e.g. as part of a logging or instrumentation effort.

**Comment by ploeh** [comment] 2016-04-07 20:28
In order to experiment further, I tried to run the above repro code against _xUnit.net 1.9.2_, and with the following NuGet package configuration, **all tests pass**:

```C#
PM> Get-Package

Id                                  Version
--                                  -------
AutoFixture                         {3.43.0
AutoFixture.Xunit                   {3.43.0
xunit                               {1.9.2}
xunit.extensions                    {1.9.2}
```

AutoFixture support for _xUnit.net 1.x_ is implemented in a separate library, but [the source code for that version of the `[AutoData]` attribute](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net/AutoDataAttribute.cs) is identical to the one that supports _xUnit.net 2_.

This corroborates the theory that something is happening inside of _xUnit.net 2_ that triggers reads of properties.

**Comment by ploeh** [comment] 2016-04-07 21:14
[According to the 'official' _xUnit.net_ Twitter account, this behaviour is by design](https://twitter.com/xunit/status/718177165448056832):

> Yes: we check for serializability of the method arguments when constructing the test cases; it's a requirement for the VS test runner

Since this is intentional behaviour in _xUnit.net 2_, I'm going to close the issue, as I don't see there's much we can do about it.

As demonstrated by the above repro, if you really need to test a class where reads of properties have side-effects, this is still possible by using a `[Fact]` with a `Fixture` instance.

There are legitimate reasons you might want to do this (e.g. in order to test that lazy-loading of properties works correctly). In most cases, though, you should adhere to the [Command Query Separation princple](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation) and make Queries (reads) side-effect-free.

**Closed by ploeh** 2016-04-07 21:14 UTC

**Comment by Sylapse** [comment] 2016-04-18 18:41
Thanks for all the info. Yes lazy loading was the scenario although not because I particularly wanted it to be lazy... After posting the issue I discovered a feature of autofac that allowed me to refactor out the lazy loading behaviour.

What I was doing originally was resolving view models and then passing in initialization data via Init methods. The properties were then using the intialization data to go and fetch more data.

Then i discovered autofacs delegate factories, which allowed me to pass in all the data into the constructor and use it accordingly. Then the viewmodels were ready for use without Init methods or any logic in the properties.

Thanks again for the detailed response!
