### ISSUE TITLE
nuget package v 3.50.3 dll is version as 3.50.0 instead of .3

### ISSUE THREAD

**Issue by minoseah629** [AutoFixture/AutoFixture#786] opened 2017-07-26 16:54 UTC
Autofixture 3.50.3 dll is not versioned correctly. 

![image](https://user-images.githubusercontent.com/1980068/28633252-26528eba-7201-11e7-9c10-bd7fb80b03cf.png)

Compared to 3.50.2 dll

![image](https://user-images.githubusercontent.com/1980068/28633255-2a9db792-7201-11e7-8c31-fc86bb7ba534.png)

I had to adjust my app.config to reflect this: 
`<dependentAssembly>
        <assemblyIdentity name="Ploeh.AutoFixture" publicKeyToken="b24654c590009d4f" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.50.3.0" newVersion="3.50.0.0" />
      </dependentAssembly>`

**Comment by zvirja** [comment] 2017-07-26 17:55
Thanks for reporting the issue. Actually, that is an [intentional](https://github.com/AutoFixture/AutoFixture/pull/763) change as the `patch` should not be a part of the AssemblyVersion. The previous version which had incorrect versioning and it has been fixed. Please refer to the mentioned PR for more detail. 

This "anomaly" will be normalized as soon as we release the next minor update (so the version will be `3.50.4.0`)

Usually that change should not be an issue and it's quite strange why you need the assembly version redirects in your solution. Did you update the AutoFixture assemblies partially (e.g you updated the `AutoFixture`, but kept the previous version of the `AutoFixture.xUnit2`)? If so, what is the reason and why update of all the assemblies is not an option?

**Comment by minoseah629** [comment] 2017-07-26 22:04
The reason why this even came up is because I use a visual studio plugin test coverage tool called ncrunch.  Whenever ncrunch would try to execute my tests, it would throw an exception and not execute any of my tests.  

System.InvalidCastException: Unable to cast object of type 'Xunit.Sdk.ReflectionAssemblyInfo' to type 'Xunit.Abstractions.IAssemblyInfo'.

So when I eventually determined that this was the cause, I felt obliged to report an issue.

**Comment by zvirja** [comment] 2017-07-26 22:12
Could you confirm that you have upgraded all the AutoFixture related assemblies in your solution? It looks like this is the reason. 

If that is not the case, could attach a simple project which demonstrates the issue, so I could have a look? I have teammates with NCrunch 3 installed, so I could check that on my side just out of curiosity. It looks quite weird O_o

In any case, it's great that you reported the issue and a way to solve it - somebody else could find it. Next minor update should fix this issue completely, so let's keep everything as is.

**Comment by minoseah629** [comment] 2017-07-26 22:51
![image](https://user-images.githubusercontent.com/1980068/28647143-628e9f04-7233-11e7-985a-154c1f0b83d4.png)

**Comment by zvirja** [comment] 2017-07-27 08:27
Great! And what about a sample of project where the issue is reproducible? It that possible to provide it? 

Thanks.

**Comment by minoseah629** [comment] 2017-07-27 12:41
your last response said if not autofixture 3.50.3 and my project is using 3.50.3, so i thought that it met the condition to not provide a sample and i dont know what sample project to provide.

**Comment by zvirja** [comment] 2017-07-27 12:47
Thanks for the reply. In this case I'll close the issue as no action seems to be required as there is a workaround till the next minor release.

**Closed by zvirja** 2017-07-27 12:47 UTC
Labels: question
