### ISSUE TITLE
Dependency against old FakeItEasy version?

### ISSUE THREAD

**Issue by andrewk-iq** [AutoFixture/AutoFixture#693] opened 2016-08-15 16:05 UTC
I'm using:
- AutoFixture 3.50.1
- AutoFixture.AutoFakeItEasy 3.50.1
- AutoFixture.Xunit2 3.50.1
- FakeItEasy 2.2.0
- Xunit 2.0.0

I'm writing tests that extend Xunit's AutoData attribute to add the AutoFakeItEasy customization, and then use abstract class types in the test method parameters. The expected behaviour is that FakeItEasy will handle the creation of the abstract type test doubles, however instead I'm getting the following exception:

> Could not load type 'FakeItEasy.Creation.IFakeOptionsBuilder`1' from assembly 'FakeItEasy, Version=2.2.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c'.

Stack trace:

>    at Ploeh.AutoFixture.AutoFakeItEasy.FakeItEasyMethodQuery.FakeMethod`1.Invoke(IEnumerable`1 parameters)
>    at Ploeh.AutoFixture.Kernel.MethodInvoker.Create(Object request, ISpecimenContext context)

Here's some test code to replicate this exception:

``` c#
using Ploeh.AutoFixture;
using Ploeh.AutoFixture.AutoFakeItEasy;
using Ploeh.AutoFixture.Xunit2;
using Xunit;

namespace Tests
{
    public abstract class AbstractClass
    {
    }

    public class AutoFixtureBugTest
    {
        public class ArrangeAttribute : AutoDataAttribute
        {
            public ArrangeAttribute() : base(new Fixture().Customize(new AutoFakeItEasyCustomization())) { }
        }

        [Theory, Arrange]
        public void TestMethod(AbstractClass test)
        {
        }
    }
}
```

Looking through FakeItEasy's github repo, I noticed that there hasn't been a FakeItEasy.Creation.IFakeOptionsBuilder since version 1.25.3; the interface appears to have been renamed to IFakeOptions since version 2.0.0. 

So this leads me to wonder, was the AutoFixture 3.50.1 nuget package built against a pre-2.0.0 version of FakeItEasy?

**Comment by ploeh** [comment] 2016-08-15 17:44
Since you're using different versions of the various libraries than the glue libraries were compiled against, have you tried adding the appropriate assembly binding redirects?

**Comment by jupaol** [comment] 2016-09-01 21:43
Was this ever fixed? I'm having the same problem with:

AutoFixture 3.50.2 
AutoFixture.AutoFakeItEasy 3.50.2
FakeItEasy 2.2.0

**Comment by ploeh** [comment] 2016-09-02 13:51
After some investigation, this seems to be related to the way FakeItEasy 2 creates abstract base class instances. When [testing compatibility with interfaces, everything seems to work](https://github.com/AutoFixture/AutoFixture/pull/672), but apparently, it looks like this isn't the case for abstract classes.

Perhaps @blairconrad has some insights on this...

**Comment by ploeh** [comment] 2016-09-02 13:54
IOW, this works:

```C#
public class Class1
{
    [Fact]
    public void Test()
    {
        var fixture = new Fixture().Customize(new AutoFakeItEasyCustomization());
        var foo = fixture.Create<IFoo>();
        Assert.NotNull(foo);
    }
}
```

but this doesn't:

```C#
public abstract class AbstractClass { }

public class Class1
{
    [Fact]
    public void Test()
    {
        var fixture = new Fixture().Customize(new AutoFakeItEasyCustomization());
        var foo = fixture.Create<AbstractClass>();
        Assert.NotNull(foo);
    }
}
```

**Comment by blairconrad** [comment] 2016-09-02 13:57
Thanks for thinking of me, @ploeh. Will investigate over the next day or so. (In UTC-4, so my activities are constrained right now).

**Comment by blairconrad** [comment] 2016-09-02 14:50
I think I understand the cause.

Pre-2.0, FakeItEasy's `Fake<T>` class had this constructor:

```c#
public Fake(Action<IFakeOptionsBuilder<T>> options)  
```

But in 2.0, we changed to

```c#
public Fake(Action<IFakeOptions<T>> optionsBuilder) 
```

because `IFakeOptionsBuilder` wasn't quite the right name for this concept, and we wanted the name for elsewhere.

So, AutoFixture compiles against FakeItEasy 1.7.whatever, and it thinks that `Fake<T>` has the first constructor. Then it calls

```c#
return new Fake<T>(
    b => b.WithArgumentsForConstructor(parameters));
```

Thinking that `b` is an `IFakeOptionsBuilder<AbstractClass>`.

I expect our (my) testing with AutoFixture and FakeItEasy 2.0 passed because we just dropped FIE 2.0 into the AutoFixture sandbox, rebuilt the world, and so `Ploeh.AutoFixture.AutoFakeItEasy.UnitTest.FixtureIntegrationTest.FixtureAutoFakesAbstractType` passed.

I'm not sure what to do without reinstating AutoFixture.AutoFakeItEasy2.

One partial workaround would be to call `new Fake<T>()`.in the case that we want to use the faked class's parameterless constructor. But that only helps with classes that have parameterless constructors. That's not particularly satisfying.

**Comment by blairconrad** [comment] 2016-09-02 15:03
In case it becomes relevant, the type was renamed in FakeItEasy/FakeItEasy#520.

**Comment by ploeh** [comment] 2016-09-02 15:39
> I'm not sure what to do without reinstating AutoFixture.AutoFakeItEasy2.

That's still an option. The code base is still around, and is being published with each new release (it's just unlisted in NuGet.org).

**Comment by blairconrad** [comment] 2016-09-02 16:29
Yeah, I saw the code.

It occurred to me while I was out strolling that if we tried to locate the `Fake<T>` constructor by reflection and build up an appropriate `b => b.WithArgumentsForConstructor(parameters)` that way, we may be able to support 1.x and 2.x FakeItEasy without users having do anything.

I bet the code would be ugly. And I'm not _entirely_ sure it's possible, but it might work.

Would you be interested?

**Comment by blairconrad** [comment] 2016-09-02 16:31
> The code base is still around, and is being published with each new release (it's just unlisted in NuGet.org).

So... right now users of FakeItEasy 2.0 and AutoFixture could probbaly grab the latest published AutoFakeItEasy2, a modern AutoFixture, a modern FakeItEasy, and get a working solution with the appropriate binding redirects? To tide them over until something better comes along?

**Comment by blairconrad** [comment] 2016-09-02 16:42
>  probably grab the latest published AutoFakeItEasy2, a modern AutoFixture, a modern FakeItEasy, and get a working solution

Confirmed. You do get the annoying 

> warning CS0618: 'AutoFakeItEasyCustomization' is obsolete: 'The AutoFakeItEasy2 package has been retired; use the AutoFakeItEasy (without the trailing "2") package instead. Details: it's turned out that it's possible to enable AutoFakeItEasy to also work with FakeItEasy 2. From version 3.49.1, you should be able to use AutoFakeItEasy with FakeItEasy 2 by adding an assembly binding redirect. This enables us, the maintainers of AutoFixture, to maintain only one code base for FakeItEasy, instead of two. If this causes problems, please create an issue at https://github.com/AutoFixture/AutoFixture/issues. We apologise for any inconvenience this may cause.'

though.

**Comment by ploeh** [comment] 2016-09-03 08:53
At the moment you get those compiler warnings (which you can suppress with a `pragma` directive), but we could remove the `[Obsolete]` attributes from that library if we decide that that's the way to go.

**Comment by blairconrad** [comment] 2016-09-04 18:36
You hate the fix?

**Comment by adamralph** [comment] 2016-09-04 18:45
No, not at all. I think it's a good solution.

**Comment by adamralph** [comment] 2017-02-19 17:56
Note that FakeItEasy 3.0.0 is due out soon, see https://github.com/FakeItEasy/FakeItEasy/issues/902

**Comment by pmcevoy** [comment] 2017-02-23 11:04
Gents, AutoFixture.AutoFakeItEasy2 is  not listed on nuget (including pre-releases) - how can I get this package?

**Comment by blairconrad** [comment] 2017-02-23 11:34
Glad you got it, @pmcevoy. For anyone else reading it,  [the package is listed](https://www.nuget.org/packages/AutoFixture.AutoFakeItEasy2/), just no versions. They still exist, but have been delisted.
Version [3.50.2](https://www.nuget.org/packages/AutoFixture.AutoFakeItEasy2/3.50.2) is the latest, which depends FakeIteasy >= 2.0.0. and  AutoFixture >= 3.50.2.

**Comment by oleksiishevchuk** [comment] 2017-03-01 15:14
@adamralph @blairconrad Hi guys.

In AutoFakeItEasy2 I see the following comment, but it is not quite clear how to do it. Could you please provide an example of bindingredirects which should be used to make it functioning?

> "The AutoFakeItEasy2 package has been retired; use the AutoFakeItEasy (without the trailing \"2\") package instead. Details: it's turned out that it's possible to enable AutoFakeItEasy to also work with FakeItEasy 2. From version 3.49.1, you should be able to use AutoFakeItEasy with FakeItEasy 2 by adding an assembly binding redirect. This enables us, the maintainers of AutoFixture, to maintain only one code base for FakeItEasy, instead of two. If this causes problems, please create an issue at https://github.com/AutoFixture/AutoFixture/issues. We apologise for any inconvenience this may cause."

**Comment by blairconrad** [comment] 2017-03-01 15:55
@oleksiishevchuk the general procedure is outlined
at [Redirecting Assembly Versions](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx?f=255&mspperror=-2147217396#Anchor_2).

However, note that this will not work for you if you fake classes instead of interfaces. You'll get the error listed in this issue. Sadly, until (unless) my fix for this issue is merged, if you want to use AutoFixture + FakeItEasy to fake classes, AutofFakeItEasy2 is the only game in town. :(

**Comment by oleksiishevchuk** [comment] 2017-03-01 16:35
@blairconrad Ah. Thanks for the quick reply.. Yeah, I have an issue with abstract classes. Your comment is very valuable, at least it is clear that we should use AutofFakeItEasy2 for now. Is there any chance that your PR will be merged soon? or you don't aware about it?

**Comment by blairconrad** [comment] 2017-03-01 16:53
@oleksiishevchuk, sadly I have no knowledge. It seems that merging would have to wait for a new AutoFixture governance model to be established. See #703 for more details.

**Closed** 2017-07-05 08:50 UTC
Labels: question

**Comment by zvirja** [comment] 2017-07-05 09:50
Released as v3.50.3

**Comment by moodmosaic** [comment] 2017-07-05 10:00
>Released as v3.50.3

@zvirja, are you on Twitter? If so, maybe you could tweet about this? 😃

**Comment by blairconrad** [comment] 2017-07-05 10:27
@moodmosaic, @zvirja, http://twitter.com/autofixture seems to be available.
Over at FakeItEasy International, we've enjoyed having an account for the organization.

**Comment by ploeh** [comment] 2017-07-05 11:23
Congratulations on releasing a new version of AutoFixture 🎉

> http://twitter.com/autofixture seems to be available.

In that vein, I (still) own autofixture.com, autofixture.net, autofixture.org, and autofixture.dk (because I'm Danish). If there was an organisation that could take ownership of those domain names, I don't mind handing them over.

Taking care of domain names requires the presence of some sort of legal entity, plus an organisation that can bear the (small) cost of domain name renewal.

As @jongalloway [mentioned in another thread](https://github.com/AutoFixture/AutoFixture/issues/703#issuecomment-292835837), the _.NET Foundation_ could be an option.

**Comment by zvirja** [comment] 2017-07-05 22:26
@moodmosaic I'm registered there, but don't have any tweats so far.. 

It might be a good idea to create an official AutoFixture account like it was suggested above and use it for such announcements. 

@ploeh That's cool that you have reserved that domains! ATM I don't know how we can use them, but later we might want to place some documentation there.. Unfortunately, currently I don't have enough time to investigate Net Foundation further and perform actions in that direction.. Probably, will allocate some time in future to see whether it's realistic and what are the benefits/requirements.

**Comment by zvirja** [comment] 2017-07-19 09:30
I've created a twitter account for us: [https://twitter.com/autofixture](https://twitter.com/autofixture). I'll post information about new releases there.

@AutoFixture/core could you please reach out to me via email (find it in the commit history) so I'll share the credentials with you?

@moodmosaic I see that your twitter account is alive, so it would be nice if you could care about our one as well (e.g. reply if needed). Is that possible? :)

@ploeh Could you please retweet the welcome tweet, so people will see it? 😉

**Comment by moodmosaic** [comment] 2017-07-21 06:39
>@AutoFixture/core could you please reach out to me via email (find it in the commit history) so I'll share the credentials with you?

Having the credentials for the https://twitter.com/autofixture account is fine by me. @zvirja, IIRC, you have my email address already for this, so you're free to send them over via email.

>@moodmosaic I see that your twitter account is alive, so it would be nice if you could care about our one as well (e.g. reply if needed). Is that possible? :)

For backup reasons, I'm fine storing the credentials in a safe place, but I don't have enough time to monitor the AutoFixture twitter account.

If someone with a question mentions the AutoFixture twitter account, then feel free to /cc me on Twitter ([@nikosbaxevanis](https://twitter.com/nikosbaxevanis)), and I'll try to reply if I have helpful answers.
