### ISSUE TITLE
3.36.10 nuget is acting weird (broken ?)

### ISSUE THREAD

**Issue by centur** [AutoFixture/AutoFixture#468] opened 2015-11-11 01:10 UTC
I've upgraded my SemanticComparison nuget from 3.36.8 to 3.36.10 and  started to get some weird message
```
Severity	Code	Description	Project	File	Line
Error	CS0012	The type 'Likeness<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Ploeh.SemanticComparison, Version=3.18.0.0, Culture=neutral, PublicKeyToken=b24654c590009d4f'.	....
```

I've downgraded it back down to 3.36.8 and all got back to normal.
It feels that latest release is broken

**Comment by mrinaldi** [comment] 2015-11-11 11:31
I had a problem with that version too and had to downgrade: https://github.com/fsprojects/Paket/pull/1202.

3.36.10 was released with no signature (strong name).
That might be the cause of your problem.

Maybe @ploeh should release a new version.

**Comment by moodmosaic** [comment] 2015-11-12 10:54
Thank you for reporting this! I'd be interested to reproduce it on my machine, but I don't know how :confused:

I've installed SemanticComparison, and xUnit.net, and I was able to compile and run successfully a non-trivial example, as shown [here](http://stackoverflow.com/a/33545239/467754).

Here's what the NuGet `get-package` command prints in the Package Manager Console:

```                                   
SemanticComparison                  {3.36.10}                                       
xunit                               {1.8.0.1549}                                    
xunit.extensions                    {1.8.0.1549}
```

**Comment by mrinaldi** [comment] 2015-11-12 12:06
The catch here is you need to reference and use one lib that depends on strong-named `SemanticComparison`.

I was able to reproduce after installing `SemanticComparisonExtensions` and using one of it's extensions methods.

For instance: `new Likeness<object, object>(null).WithInnerLikeness(p => p.ToString(), p => p.ToString(), p => p);`

**Comment by ploeh** [comment] 2015-11-12 12:07
Thank you for reporting this :+1: 

I downloaded a sample of AutoFixture NuGet packages to investigate further:

```
- AutoFixture                         {3.36.10}
- AutoFixture.AutoMoq                 {3.36.10}
- AutoFixture.Idioms                  {3.36.10}
- AutoFixture.Xunit2                  {3.36.10}
- SemanticComparison                  {3.36.10}
```

All of these packages are *unsigned*. From that sample, my hypothesis is that all version 3.36.10 packages are unsigned.

Since the old build server had been increasingly unreliable, we changed to a new build server. AutoFixture 3.36.10 is the first release from the new build system. Apparently, we either forgot to sign the assemblies, or something went wrong in the build. We'll need to investigate exactly what the problem is. Hopefully @ecampidoglio can help us with this.

This was definitely *not* intentional, so I've now unlisted all AutoFixture 3.36.10 packages from NuGet. While these packages still exist, they'll not show in listings. AutoFixture 3.36.9 is at the moment the latest official release.

**Comment by ecampidoglio** [comment] 2015-11-12 15:32
I confirm that the NuGet packages produced by the new build aren't signed. Totally my fault. :disappointed:

In order to sign the assemblies in [AppVeyor](https://ci.appveyor.com/project/AutoFixture/autofixture), we need to add the key file (_*.sn_) to the repository. However, since sharing the private key publicly defeats the idea of digital signatures, we should [encrypt the file with a symmetric key and store it securely in the build definition](http://help.appveyor.com/discussions/questions/217-signing-net-assemblies-without-exposing-the-snk-file-publicly).

**Comment by ecampidoglio** [comment] 2015-11-12 15:34
For `v4`, we might want to consider dropping strong naming altogether. Personally, I don't see the value of digitally signing the binaries of an open source testing library such as AutoFixture. Many open source licences – including [MIT](https://opensource.org/licenses/MIT) which is the one [we use](https://github.com/AutoFixture/AutoFixture/blob/master/LICENCE.txt) – explictily state that the software is provided _as-is_. Also, the fact that's being published through NuGet is itself a guarantee of the origin of the binaries, since only the possessors of the right API key can publish the packages.

However, this is [open for debate](http://nuget.codeplex.com/discussions/247827?ProjectName=nuget). :wink:

**Comment by ploeh** [comment] 2015-11-12 19:50
@ecampidoglio, while I digest all of this, can you please disable the NuGet publication step on AppVeyor, so that we don't publish another unsigned package?

**Comment by ecampidoglio** [comment] 2015-11-12 20:08
@ploeh Done :+1:

**Comment by ploeh** [comment] 2015-11-16 16:57
For now, I've set up AutoFixture so that I can simply build and publish it on my own laptop, which is basically the same setup I've been quite happy with when developing [Albedo](https://github.com/ploeh/Albedo), [Hyprlinkr](https://github.com/ploeh/Hyprlinkr), [ZeroToNine](https://github.com/ploeh/ZeroToNine), and [AtomEventStore](https://github.com/GreanTech/AtomEventStore).

Using that mechanism, I've now published [AutoFixture 3.36.11](https://www.nuget.org/packages/AutoFixture/3.36.11), including [SemanticComparison 3.36.11](https://www.nuget.org/packages/SemanticComparison/3.36.11), which, as far as I can tell, are all signed.

@centur Does that address your immediate problem?

**Comment by ploeh** [comment] 2015-11-25 08:04
Closing, as I've heard no further complaints about this for more than a week now.

**Closed by ploeh** 2015-11-25 08:04 UTC
Labels: bug

**Comment by centur** [comment] 2015-11-25 10:16
Sorry about not getting back to this, I think I've missed the notification. But anyway - I haven't had a chance yet to upgrade all packages again. Once I will - I'll drop a line here, but I assume that this is fixed
