### ISSUE TITLE
AutoMoqCustomization sets up verifiable on method that returns objects

### ISSUE THREAD

**Issue by jnordtorp-foreflight** [AutoFixture/AutoFixture#1281] opened 2021-07-06 08:45 UTC
If i Freeze an interface with a method returning an object, and this method is called during execution, the mock expects its setup during a verify call.

```C#
        [TestInitialize]
        public void Setup()
        {
            Fixture = new Fixture().Customize(new AutoMoqCustomization());
        }

        [TestMethod]
        public void Test()
        {
            var mock = Fixture.Freeze<Mock<ITestInterface>>();
            mock.Setup(x=> x.MethodA(It.IsAny<string>())).Returns(new {test = "test"}).Verifiable();

            var sut = Fixture.Create<SUT>();

            sut.Run();

            mock.Verify();
        }

        public interface ITestInterface {

            public object MethodA(string a);
            public object MethodB(string b);
        }


        public class SUT
        {

            private ITestInterface TestInterface;

            public SUT(ITestInterface testInterface){
                TestInterface = testInterface;
            }

            public void Run(){
                TestInterface.MethodA("a");
                TestInterface.MethodB("b");
            }

        }
```

This test fails with the message: 

> ITestInterface mock => mock.MethodB("b"):
   This setup was not matched.
    at Moq.Mock.Verify(Func`2 predicate)
   at Moq.Mock.Verify()

On the other hand, if i change the return type of `Method A` and `Method B` to be strings, it parses.
It also parses if i change the `Fixture` customization:

```C#
        [TestInitialize]
        public void Setup()
        {
            Fixture = new Fixture().Customize(new AutoMoqCustomization
            {
                ConfigureMembers = true
            });
        }
```

Expected behavior is that it behaves the same way it handles non objects, that is, that methods are not verifiable unless i want them to be.

**Comment by aivascu** [comment] 2021-07-19 21:10
@jnordtorp-foreflight I am unable to reproduce the issue. The example you provided passes.
Please check that you have installed the latest versions of the packages including the latest version of `Moq` and recheck the example.
Closing for now. Feel free to reopen when you find a reproducible example.

**Closed by aivascu** 2021-07-19 21:10 UTC
