### ISSUE TITLE
Does AutoFixture support .NET Core 3.1 and .NET 5?

### ISSUE THREAD

**Issue by rathoregee** [AutoFixture/AutoFixture#1286] opened 2021-08-29 00:34 UTC
Autofixture has .NET platforms compatibility table
for 

.NET Framework | .NET Standard

What about .netcore 3.1 and .net 5.0? 

AutoMoqDataAttribute does not work there!!

**Comment by aivascu** [comment] 2021-08-29 09:05
@rathoregee this question has already been answered, on several occasions [here](https://github.com/AutoFixture/AutoFixture/discussions/1255) and on SO. 

The short answer is, AutoFixture is compatible with .NET Core, .NET 5 and should remain compatible with future versions.

If you have encountered a bug in one of the libraries please raise an issue and provide a minimum reproducible example.

Closing the issue.

**Closed by aivascu** 2021-08-29 09:05 UTC

**Comment by Kralizek** [comment] 2021-08-29 10:42
@rathoregee I use regularly AutoMoq in a project running on .NET 5 (and testing .NET 6) and I don't have any issue. As a quick suggestion, make sure to also have a direct reference to Moq so that you are sure you're importing the latest version.

**Comment by rathoregee** [comment] 2021-08-30 12:02
For example i cannot use like this
public class AutoMoqDataAttribute : AutoDataAttribute
{
    public AutoMoqDataAttribute()
        : base(new Fixture()
            .Customize(new AutoMoqCustomization()))
    {
    }
}

It ask to use add         [System.Obsolete]



using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit2;

namespace PdfUploder.Tests.UnitTests
{
    public class AutoMoqDataAttribute : AutoDataAttribute
    {
        [System.Obsolete]
        public AutoMoqDataAttribute()
            : base(new Fixture()
                .Customize(new AutoMoqCustomization()))
        {
        }
    }
}

**Comment by aivascu** [comment] 2021-08-30 12:35
@rathoregee it tells you the constructor is obsolete because that particular overload of the constructor is obsolete, and you should probably use another constructor overload. This has nothing to do with the target .NET framework version.

The recommended constructor overload is `AutoMoqCustomization(Func<IFixture> factory)`. This means your custom AutoData attribute should look like this:

```cs
using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit2;

namespace PdfUploder.Tests.UnitTests
{
    public class AutoMoqDataAttribute : AutoDataAttribute
    {
        public AutoMoqDataAttribute()
            : base(() => new Fixture()
                .Customize(new AutoMoqCustomization()))
        {
        }
    }
}
```

**Comment by rathoregee** [comment] 2021-08-30 13:42
OK... now i am using like this


using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit2;
using System.Linq;

namespace PdfUploder.Tests.UnitTests
{
    public class AutoMoqDataAttribute : AutoDataAttribute
    {      
        public AutoMoqDataAttribute() : base(() =>
        {
            var fixture = new Fixture().Customize(new CompositeCustomization(
                new AutoMoqCustomization(),
                new SupportMutableValueTypesCustomization()));

            fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList().ForEach(b => fixture.Behaviors.Remove(b));
            fixture.Behaviors.Add(new OmitOnRecursionBehavior());

            return fixture;
        })
        {
        }
    }
}

but IFormFile all propeties are coming NULL what the point ?

 ![bug](https://user-images.githubusercontent.com/18663732/131348318-c2eb0913-8ca0-4ef0-a6ee-55d0ff29db32.png)

string ContentDisposition { get; }
string ContentType { get; }       
string FileName { get; }


My understadnig it should provide an prepared object
when you use the attr..
like
[Theory(DisplayName = "Valid pdf upload casev0 "), AutoMoqData]

can you provide any working code or example to solve IFormFile issue or to create a object from it. thanks for help so far

**Comment by aivascu** [comment] 2021-08-30 15:04
@rathoregee behind the covers `IFormFile` is generated as a mock, and by default Moq does not generate any values for the members.

If you want AutoFixture to generate the member values you should configure the `AutoMoqCustomization` to generate member data for the members by setting the property `ConfigureMembers` to `true`.

```cs
new AutoMoqCustomization { ConfigureMembers = true  }
```
