### ISSUE TITLE
🐛 Record and using IPostprocessComposer.without()

### ISSUE THREAD

**Issue by ThijsBaan** [AutoFixture/AutoFixture#1360] opened 2022-07-26 11:42 UTC
### Describe the Bug
In .NET6, on AutoFixture version 4.17.0, fixture is ignoring the ` IPostprocessComposer.without()` on a record, it assigns a default value and ignores the without.

### Scenario
This record has a two properties. I set fixture to not include `Street`. The field is getting filled by AutoFixture.
```
[TestClass]
public class DummyClass
{

    public record Address(string City, string Street);

    [TestMethod]
    public void MyRecordTest()
    {
        var fixture = new Fixture();
        var address = fixture.Build<Address>()
            .Without(s => s.Street)
            .Create();


        Assert.IsNotNull(address);

        Assert.IsNotNull(address.City);

        Assert.IsNull(address.Street); // fail
    }
}
```

Do note, a record implementation like this also fail:
```
    public record Address(string City, string Street)
    {
        public string City { get; set; } = City;
        public string Street { get; set; } = Street;
    }
```
### Expected Behavior
I'd expect that `Street` would be excluded and have the value `null`, just like it would be if the record was a class. 

### Screenshots
![image](https://user-images.githubusercontent.com/36266364/180997532-c894385e-dec8-413c-a8d6-6a958f0cb6e2.png)

Thanks!

**Comment by GeraldLx** [comment] 2022-07-26 14:22
First of all AutoFixture was created way before Microsoft introduced records. So Record support was not taken into consideration when the Api was designed, but it works.

As a record is basically a class with autogenerated code, you can emulate a simplified record of:
```
public record Address(string City, string Street);
```
with:
```
public class Address
{
  public Address(string City, string Street)
  {
    City = city;
    Street = street;
  }

  public string City { get; init; }

  public string Street { get; init; }
}
```

So this is the view AutoFixture has on your record.

And that is happening with your code. You are asking AutoFixture to generate a class with a constructor taking 2 arguments of type string. And that is happening behind the scenes.

After creating the Address instance, AutoFixture looks on the properties and fills them. 

Your Without statement suppresses the setting of the property Street, but your test just checks, if Street is null and does not care if the Street was set in constructor or via property.

So I would not say that this is a bug, this is by design.

To make your test work, you must write your record like this:
```
public record Address
{
  public string City { get; init; }
  
  public string Street { get; init; }
}
```

**Comment by aivascu** [comment] 2022-07-29 06:18
This is a known issue and it is planned to be released in the [next major version](https://github.com/AutoFixture/AutoFixture/discussions/1327). After some delay the work on v5 should resume in August.
There's a draft of constructor customizations, which will be used to mitigate the issue with constructor-only records and fully encapsulated types, in the [AutoFixture.Community.Extensions](https://github.com/aivascu/AutoFixture.Community.Extensions) package.
Closing the issue.

**Closed by aivascu** 2022-07-29 06:18 UTC
Labels: bug
