### ISSUE TITLE
Setup Property that does not have a default ctor

### ISSUE THREAD

**Issue by Epibatidin** [AutoFixture/AutoFixture#587] opened 2016-03-24 17:03 UTC
Hi 

we have a large Application with some Interfaces that require CultureInfo objects, this is for PriceRendering etc.
we used Moq with AutoFixture.AutoMoq for long time and it worked well. 
i think the relevant part is Moq version 4.1.1311.0615 and AutoFixture(.AutoMoq) 3.18.1
we updated to Moq 4.2.1510.2205 and AutoFixture(.AutoMoq) 3.42.0 

after that the following test fails with a Exception from Castle 
{"Can not instantiate proxy of class: System.Globalization.CultureInfo.\r\nCould not find a parameterless constructor."}

```C#
public interface ICultureInfoHolder
{
	CultureInfo Culture { get; set; }
}

[Fact]
public void SetupACultureInfo()
{
	var fixture = new Fixture();
	fixture.Customize(new AutoMoqCustomization());

	var cultureHolder = fixture.Create<Mock<ICultureInfoHolder>>();
	var c = cultureHolder.Object.Culture; // here it throws
}
```

i debugged through the code and the multiple extension points of Fixture customization but cant find the point where some 
component says - create a object of type CultureInfo.

**Comment by tiesmaster** [comment] 2016-03-25 08:55
Seems like a duplicate of #427. @Epibatidin It looks like you're running an older version of AutoFixture. If you update to [version 3.34.2](https://github.com/AutoFixture/AutoFixture/issues/441#issuecomment-140855082) or later, it should work.

**Comment by Epibatidin** [comment] 2016-03-25 12:26
I am not exactly sure if this solves the problem.
There is a setup for CultureInfo registered in fixture i skipped that in the description because i dont think it was relevant.
We use Version 3.42.0 and wont downgrade to 3.34.2

If setuped, Fixture is capable of creating CultureInfos. 
I think its some major shortcoming with Objects that does not have Default Ctors or it is a design decision i am not sure.

Following test is not directly related to CultureInfo but does also fail because of missing default Ctor.


`
public interface IHolder
    {
        MyDummy Dummy { get; set; }
        CultureInfo Culture { get; set; }        
    }

    public class MyDummy
    {
        public MyDummy(string someValue) { }
    }

    class Class1
    {
        [Test]
        public void should_name()
        {
            var fixture = new Fixture();
            fixture.Customize(new AutoMoqCustomization());
            fixture.Customize<CultureInfo>(r => r.FromFactory(() => new CultureInfo("de-DE")));

            var holder = fixture.Create<Mock<IHolder>>();


            var dummy = holder.Object.Dummy;  // fails
            var culture = holder.Object.Culture;   // fails too
        }
    }
`

**Comment by tiesmaster** [comment] 2016-03-25 12:54
Ah, now I see. This is not really a problem with AutoFixture, but with Moq. Since you're using them together, it's easy to overlook that. The moq that you asked AutoFixture to create for you is similar to this call:

````csharp
    var mockedHolder = new Mock<IHolder>() { CallBase = true, DefaultValue = DefaultValue.Mock };
````

Which is documented [here](https://github.com/Moq/moq4/wiki/Quickstart#customizing-mock-behavior): it will setup all methods and properties to mock it using Moq. However, without a default constructor, Moq won't know how to instantiate it: the thing you ran into.

In this case, you probably want to use the other [AutoMoq customization](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#auto-configured-mocks):

````charp
    fixture.Customize(new AutoConfiguredMoqCustomization());
````

With this customization, it won't throw, since AutoFixture does know how to deal with non-default constructors ;)

**Comment by ploeh** [comment] 2016-03-25 13:25
Thank you for submitting this issue. Isn't this is a duplicate of #434?

If it is, it's an issue with Moq reported here: https://github.com/moq/moq4/issues/196

**Comment by tiesmaster** [comment] 2016-03-25 14:04
@ploeh He's not using `AutoConfiguredMoqCustomization`, but `AutoMoqCustomization`.

**Comment by ploeh** [comment] 2016-03-27 12:13
What @tiesmaster [writes](#issuecomment-201268130) also reflects my current understanding of the problem. The reason I thought this was related to #434 was because that issue is about a breaking change in Moq, and that might explain why upgrading would cause a break. Apparently, that was a red herring.

It makes sense to me that it doesn't work. What I don't understand is why it would have ever worked. In order to investigate, I created a new C# project and installed the following NuGet packages:

```
PM> Get-Package

Id                                  Versions
--                                  --------
AutoFixture                         {3.18.1}
AutoFixture.AutoMoq                 {3.18.1}
Moq                                 {4.1.1311.0615}
xunit                               {2.1.0}
xunit.abstractions                  {2.0.0}
xunit.assert                        {2.1.0}
xunit.core                          {2.1.0}
xunit.extensibility.core            {2.1.0}
xunit.extensibility.execution       {2.1.0}
```

I also added this code in order to attempt to reproduce:

```C#
public interface ICultureInfoHolder
{
    CultureInfo Culture { get; set; }
}

public class Tests
{
    [Fact]
    public void SetupACultureInfo()
    {
        var fixture = new Fixture();
        fixture.Customize(new AutoMoqCustomization());

        var cultureHolder = fixture.Create<Mock<ICultureInfoHolder>>();
        var c = cultureHolder.Object.Culture; // here it throws
    }
}
```

Despite the use of the older AutoFixture and Moq versions, the test fails at the line with the `// here it throws` comment.

This is what I'd expect.

@Epibatidin, can you provide a repro that demonstrates what worked with the earlier versions, but doesn't work now?

**Comment by Epibatidin** [comment] 2016-03-29 09:12
sry about that default ctor stuff, sure Fixture is capable of handling non default ctors thats why we use it.
I thought Moq would delegate the object creation back to autofixture. 

the original issue arised from a call to SetupAllProperties 
i tracked it down to the simple testcase i posted first. 

i build a project with the references @Ploeh listed and get the same error on autofixture. 
so i checked the original code again and yes its a duplicate of #434

the correct code for ICultureInfoHolder would be 

```
public interface ICultureInfoHolder
{
    CultureInfo Culture { get; }
}

```
sry for wasting yout time.

**Comment by ploeh** [comment] 2016-03-29 13:21
No worries; this isn't the easiest, or most discoverable, issue.

In `AutoMoqCustomization`, Moq doesn't delegate object creation back to AutoFixture, because Moq doesn't have any extensibility point that enables that.

The `AutoConfiguredMoqCustomization` attempts to rectify this situation by proactively configure all mocks, but I don't have any experience with it...

Do you have other questions or concerns, or can we close the issue?

**Comment by Epibatidin** [comment] 2016-03-30 07:57
can be closed

**Closed** 2016-03-30 12:32 UTC
