### ISSUE TITLE
Autofixture: Setting up an fixture for In-memory DbContext

### ISSUE THREAD

**Issue by takato1314** [AutoFixture/AutoFixture#1170] opened 2020-02-27 04:20 UTC
Hi,
I have make the [same post in SO](https://stackoverflow.com/questions/60430118/setting-up-an-autofixture-for-in-memory-dbcontext). Feel free to comment there.

I am currently trying to use Autofixture to create a pre-defined fixture as an implementation of [ICustomization][1] for ApplicationDbContext using [In-Memory provider][2].

```csharp
public class ApplicationDbContextFixture : ICustomization
{
    public void Customize(IFixture fixture)
    {
        var specimenFactory = new SpecimenFactory<ApplicationDbContext>(CreateDbContext);
        fixture.Customize<ApplicationDbContext>(
                composer =>
                    composer.FromFactory(specimenFactory)
                );
    }

    /// <summary>
    /// Private factory method to create a new instance of <see cref="ApplicationDbContext"/>
    /// </summary>
    private ApplicationDbContext CreateDbContext()
    {
        DbContextOptions<ApplicationDbContext> dbContextOptions = null;
        var builder = new DbContextOptionsBuilder<ApplicationDbContext>();
        var configurationOptions = new ApplicationStoreOptions
        {
            ConfigureDbContext = dbCtxBuilder =>
            {
                dbContextOptions =
                    (DbContextOptions<ApplicationDbContext>)
                    dbCtxBuilder.UseInMemoryDatabase(DatabaseName).Options;
            }
        };
        configurationOptions.ConfigureDbContext(builder);
        var dbContext = new ApplicationDbContext(dbContextOptions, configurationOptions);
        
        return dbContext;
    }
}

```
Then, I will apply that customization to my Fixture as follows:
```csharp
    [Fact]
    public void TestAddUsersToEmptyDatabase()
    {
        // Arrange
        // Fixture for ApplicationDbContext
        var fixture = FixtureFactory.CreateFixture();
        var applicationDatabaseFixture = new ApplicationDbContextFixture();
        fixture.Customize(applicationDatabaseFixture);
        
        // Fixture for users
        var randomUser = fixture.Create<AppUser>();
        var normalUser = fixture.Create<AppUser>();
        var adminUser = fixture.Create<AppUser>();

        // Act & Assert
        // Run the test against one instance of the context
        // Use a clean instance of the context for each operation too
        using (var dbContext = fixture.Create<ApplicationDbContext>())
        {
            Assert.Empty(dbContext.Users);
            dbContext.Users.Add(randomUser);
            dbContext.SaveChanges();
        }

        using (var dbContext = fixture.Create<ApplicationDbContext>())
        {
            dbContext.Users.AddRange(normalUser, adminUser);
            dbContext.SaveChanges();
        }

        using (var dbContext = fixture.Create<ApplicationDbContext>())
        {
            Assert.NotEmpty(dbContext.Users);
            Assert.NotNull(dbContext.Users.SingleOrDefault(_ => _.Id == randomUser.Id));
            Assert.NotNull(dbContext.Users.SingleOrDefault(_ => _.Id == normalUser.Id));
            Assert.NotNull(dbContext.Users.SingleOrDefault(_ => _.Id == adminUser.Id));
        }
    }
```
FixtureFactory.CreateFixture implementation
```
    /// <summary>
    /// Factory method to declare a single <see cref="IFixture"/> for unit tests applications
    /// </summary>
    internal static class FixtureFactory
    {
        internal static IFixture CreateFixture()
        {
            var fixture = new Fixture().Customize(
                new AutoMoqCustomization { ConfigureMembers = true });

            return fixture;
        }
    }
```

Now in my unit test, asserting the ```Assert.Empty(dbContext.Users);``` will throw ```System.NotImplementedException : The method or operation is not implemented.``` because the ```DbSet<AppUser> Users``` generated from Autofixture is a DynamicProxy.

See image [dbContext.Users as DynamicProxy][3]

Oddly enough if I inspect the breakpoints from the factory method (ie. ```CreateDbContext()```) called from the ```fixture.Create<ApplicationDbContext>()```, the DbSet<AppUser> Users is of the expected type.

See image [dbContext.Users as InternalDbSet][4]

Optionally, I do aware that I can replace all the usage of ```dbContext.Users``` to ```dbContext.Set<User>()``` and that would make the unit test pass but the problem is that in the actual class, I am using the ```dbContext.Users``` for [IQueryables][6] and database operations, so I still need to stick with it if possible.

Hence, I would need help to know why does AutoFixture used my factory method to generate the instance for my ApplicationDbContext but all the ```DbSet<>``` properties inside it are mocked when resolved by the ISpecimenBuilder. Is there a way to remedy this? 

I've post the similar question in [their Github][5] but it has been not active recently, so i also asked here.

Kindly please understand I only started to use Autofixture 2 days ago. So if there's something that I write wrong or there's a misconception in any Design Patterns, please kindly wrote a comment so that I can take it as a lesson.

**Update 1**:
So i tried to use initialized a plain fixture without any AutoMoq customization (ie. ```fixture = new Fixture()```) and this time it throws a ```AutoFixture.ObjectCreationExceptionWithPath``` exception, complaining that it is unable to resolve DbSet<T> property within the ApplicationDbContext. At this point, I was thinking if anyone know how to use a Relay or ISpecimenBuilder to tell Autofixture to use/call/implement all ```DbSet<T>``` properties within the ApplicationDbContext with ```dbContext.Set<T>``` because that would work if I replace all usage of DbSets in my unit tests, but as I mentioned, all IQueryable are return from DbSets so i cannot simply just replace it in ApplicationDbContext.

  [1]: https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/ICustomization.cs
  [2]: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#writing-tests
  [3]: https://i.stack.imgur.com/2xAAf.png
  [4]: https://i.stack.imgur.com/Bo7em.png
  [5]: https://github.com/AutoFixture/AutoFixture/issues/1170
  [6]: https://docs.microsoft.com/en-us/dotnet/api/system.linq.iqueryable?view=netcore-3.1

**Comment by aivascu** [comment] 2020-03-03 10:06
Hi @takato1314
I think you might want to use Microsoft's own [In-Memory](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory)/SQLite database provider instead of trying to mock the DbContext.
I have tried using many mocking libraries for EF Core but none have been able to fulfill my needs.
I hope it's not too bold of me, but you could have a look at this project I have created (EntityFrameworkCore.AutoFixture)[https://github.com/aivascu/EntityFrameworkCore.AutoFixture], since it's solving the exact issue you seem to have.
For now it's still not v1 because I am still working out a reliable deployment pipeline and the documentation, but it's very much working OK for me.

**Comment by takato1314** [comment] 2020-03-05 14:36
Hi, thx for the reply @aivascu . I will give this a try and let you know the results if there's anything I need.

**Comment by takato1314** [comment] 2020-03-05 18:19
So upon first try it seems that your solution did met the basic requirements of what i'm trying to do, ie. to use Autofixture and In-Memory Db for creating fixture for DbContext. 

However, it seems that it cannot create fixture for DbContexts if the class has custom constructor parameters than the expected DbContextOptions param. For eg, if i add an additional parameter to your [TestDbContext constructor ](https://github.com/aivascu/EntityFrameworkCore.AutoFixture/blob/e748945517baf2eb0325c9094f6330767af81d2d/src/EntityFrameworkCore.AutoFixture.Tests/Common/Persistence/TestDbContext.cs#L13), then this will break quite a lot of your unit tests, throwing the exception ``` System.MissingMethodException : Constructor on type 'EntityFrameworkCore.AutoFixture.Tests.Common.Persistence.TestDbContext' not found. ```.

For my case, I am required to create fixtures from this [ConfigurationDbContext](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/DbContexts/ConfigurationDbContext.cs) from IdentityServer4 for my integration tests.

**Comment by aivascu** [comment] 2020-03-06 07:15
Thank you for the feedback @takato1314.

I can see your point. The scenario you're describing is not something that I encountered which is why it was not implemented in the library so far.

I have created a [new issue](https://github.com/aivascu/EntityFrameworkCore.AutoFixture/issues/24) for the scenario you described, so you can track the feature implementation.
Feel free to add comments to the issue and [submit new issues](https://github.com/aivascu/EntityFrameworkCore.AutoFixture/issues), if you encounter any.

**Comment by ecampidoglio** [comment] 2020-04-20 10:10
Since the issue is being tracked in aivascu/EntityFrameworkCore.AutoFixture#24, I'm going to close this one. Feel free to reopen, if you'd like to discuss this further.

**Closed by ecampidoglio** 2020-04-20 10:10 UTC
