### ISSUE TITLE
Is AutoFixture should work with asp.net core?

### ISSUE THREAD

**Issue by arielcloud** [AutoFixture/AutoFixture#666] opened 2016-06-30 14:13 UTC
when i'm trying to install this nuget package i'm getting error:

> Package AutoFixture 3.48.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package AutoFixture 3.48.0 supports: net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by ploeh** [comment] 2016-06-30 21:26
AutoFixture isn't currently available for .NET Core. Since this is essentially a duplicate of #404, I'm going to close this issue.

**Closed by ploeh** 2016-06-30 21:26 UTC

**Comment by theutz** [comment] 2016-11-24 21:28
Has anything changed on this in the last 5 months?

**Comment by nukec** [comment] 2017-02-27 10:24
Any news on this?

**Comment by CBinet** [comment] 2017-09-04 03:55
I'm currently working on a .NET Core version something that would work a bit like AutoFixture. Will keep you guys updated when i'm finished.

**Comment by zvirja** [comment] 2017-09-04 08:03
> I'm currently working on a .NET Core version something that would work a bit like AutoFixture. W

BTW, the .NET Core support is ready, however packages have been published to the [private](https://github.com/AutoFixture/AutoFixture#vnext-feed) feed only so far. Refer to the [Gallery](https://www.myget.org/gallery/autofixture) to see whether the library you need supports .NET Core.

We are planning to have a public release in the nearby future, however we have some things to[ finish before](https://github.com/AutoFixture/AutoFixture/milestone/3).
