### ISSUE TITLE
Add a factory method overload to the .With(...) customization method

### ISSUE THREAD

**Issue by abatishchev** [AutoFixture/AutoFixture#708] opened 2016-09-24 16:19 UTC
Hi,
Currently to assign property's value in runtime using a lambda we have to add the noise of `Without()` first:

``` csharp
var entity = fixture.Build<MyEntity>()
                    .Without(x => x.SomeProperty)
                    .Do(x => x.SomeProperty = i++)
                    .Create();
```

Without `Without` the lambda is ignored and random value is assigned instead.

Is it possible to drop `Without()`? Then it would be just:

``` csharp
var entity = fixture.Build<MyEntity>()
                    .Do(x => x.SomeProperty = i++)
                    .Create();
```

Much cleaner and shorter!

Real-world example:

``` csharp
fixture.Build<EarningLineItem>()
       .With(x => x.ProgramVersionId, programVersionId)
       .With(x => x.TransactionCurrencyCode, "USD")
       .With(x => x.EarningPeriodId, fixture.Create<int>())
       .With(x => x.UsagePeriodId, fixture.Create<int>())
       .With(x => x.EarningLineItemStatusId, EarningLineItemStatus.Eligible)
       .With(x => x.CorrelationId, Guid.NewGuid().ToString())
       .With(x => x.DataEarnDate, dataEarnData ?? DateTime.Now)
       .With(x => x.TenantId, Tenant.Dummy)
       .With(x => x.GLSplitCode, _glSplitCodes.Random())
       .With(x => x.PartnerType, fixture.Create<string>().Substring(0, 5))
       .With(x => x.AgreementNumber, fixture.Create<string>().Substring(0, 10))
       .With(x => x.RootAgreementNumber, fixture.Create<string>().Substring(0, 10))
       .With(x => x.ServiceCode, fixture.Create<string>().Substring(0, 5))
       .Without(x => x.TransactionDate).Do(x => x.TransactionDate = GenerateRandomDate())
       .Without(x => x.EarningFeeTypeId).Do(x => x.EarningFeeTypeId = (byte)fixture.Create<EarningLineItemFeeType>())
       .Without(x => x.PaymentCurrencyCode)
       .Without(x => x.PaymentAmount)
       .Without(x => x.PartnerProgramEnrollmentId).Do(x => x.PartnerProgramEnrollmentId = ppeIds[programVersionId].Random())
       .Without(x => x.CompanyCode).Do(x => x.CompanyCode = companyCodeIds[x.PartnerProgramEnrollmentId].Random());
       .Without(x => x.CompanyCode).Do(x => x.TransactionCurrencyCode = currencyCodes.Random());
       .Without(x => x.EarningTypeId).Do(x => x.EarningTypeId = earningTypeIds[programVersionId].Random());
```

**Comment by abatishchev** [comment] 2016-09-29 20:29
Any response, suggestion, please?

**Comment by Zvirja** [comment] 2016-11-12 00:56
Hi,

I've checked the codebase and found that indeed such thing happens because actions are executed _before_ autoproperties are assigned.

The simplest way to work around the issue would be to omit auto-properties:
```csharp
fixture.Build<EarningLineItem>()
       .OmitAutoProperties()
       .With(m => m.Prop1)
       .Do(m => m.Prop2 = value)
       ...
```

That is not perfect, but still working solution. Does that allow you to meet your needs?

**Comment by Zvirja** [comment] 2016-11-12 01:00
One more suggestion might be to initialize properties _after_ the object is created (i.e. after the call to the `Create()` method), like that is suggested in the #344 ([see here](https://github.com/AutoFixture/AutoFixture/issues/344#issuecomment-74910796)). In this case you will need a custom extension method for this purpose.

**Comment by abatishchev** [comment] 2016-11-12 05:51
Hey Alex, thanks for coming back andclookkjgcintoc this issue.

The problem with `OmitAutoProperties()` is that it forces to explicitly opt-in and list all properties I do need. Imagine a case, when I want 10-20 properties to be auto-assigned and just 1 be assigned manually by a lambda.

**Comment by Zvirja** [comment] 2016-11-12 08:07
And what about second where you initialize object after its construction?

**Comment by abatishchev** [comment] 2016-12-06 18:50
I'm sorry, was on a parental leave with very limited access to the computer.

The thing is that there are of course various workaround but what I really would love is to rework this so no workarounds would be necessary, hope makes sense to you too.

**Comment by zvirja** [comment] 2017-07-04 12:36
@abatishchev Let me get back to this issue again 😉

Analyzing more your example I noticed the following pattern:
```csharp
.Without(x => x.TransactionDate).Do(x => x.TransactionDate = GenerateRandomDate())
```

could actually be refactored to:
```csharp
.With(x => x.TransactionDate, () => some expr)
```

This requires introduction of another overload of the `With` method that takes a `Func<T>` instead of a static value.

Could you please clarify whether introduction of the `With()` overload with factory method for value would be enough to cover your needs?

**Comment by abatishchev** [comment] 2017-07-04 19:24
Thanks a bunch for coming back on this!

Since/if the Func will be invoked everytime then yes, this would be sufficient for us.

**Comment by zvirja** [comment] 2017-08-10 10:03
@abatishchev I've found that for your case you can create your own extension method to add an API for that:
```csharp
public static IPostprocessComposer<T> With<T, TProperty>(
    this IPostprocessComposer<T> composer,
    Expression<Func<T, TProperty>> propertyPicker,
    Func<TProperty> factory)
{
    var setPropertyCommand = new BindingCommand<T, TProperty>(propertyPicker, _ => factory());
    var context = new SpecimenContext(composer);

    return composer
        .Without(propertyPicker)
        .Do(specimen => setPropertyCommand.Execute(specimen, context));
}
```
Usage will be exactly as it was mentioned above:
```csharp
.With(x => x.TransactionDate, () => some expr)
```

Notice, this extension method will work fine for the `fixture.Build<>()` customization only and will not work if you use `fixture.Customize<>` API.

**Comment by abatishchev** [comment] 2017-08-15 17:26
Can this extension method be a part of the library? Otherwise I have to clone it to each project where I'm using AutoFixture. Since With, Without, Do are most used APIs, I think it would be quite useful/popular.

**Comment by zvirja** [comment] 2017-08-16 09:57
This exact extension cannot be merged, as it doesn't cover the `fixture.Customize<>()` API.

There is the PR that implements this feature (see #794), however we need to clearly see a reason to extend AutoFixture API as we cannot handle all the ad-hoc cases. Could you please describe the _common_ situation in which you need this functionality? This will help to understand whether this feature will help to cover some _common_ scenarios, or will help only some very specific projects only.

Thank you!

**Comment by abatishchev** [comment] 2017-08-17 01:47
My scenario is the following: I generate dummy data which is sent to API and then saved into database. Table has foreign key constraints so field of type int can't be random number, it must fall into specific range. And this range is different for each field. So I'm pre-populating an array with proper/well-know values and inside Do() assign a random element from it. But before has to call Without() for every such field to opt-out from random value assigned by AutoFixture itself.
Makes sense?

**Comment by zvirja** [comment] 2017-08-17 09:32
@abatishchev To be honest, the scenario you described doesn't seem to be _common_ and looks very project specific. It's unlikely that other projects will need this feature as well. Therefore, if you have more scenarios that are more _common_, please share them to us.

@alexashley Given that you fired the PR #794, could you please share your scenarios as well?

**Comment by alexashley** [comment] 2017-08-17 15:25
@zvirja I mostly picked this issue up because it seemed like a straight-forward feature that I could see myself using. I don't have real-world, pressing scenarios, but I'd probably use it for these reasons:

- grabbing random values from a known set (like @abatishchev's example)
- generate an Object Mother with Autofixture and pass it to a function that creates a collection of random size (which I tend to prefer over setting `RepeatCount` and calling `CreateMany`)
- force some degree of randomness when using `With` (this is nice for TDD, and I assume if people are using the value overload for `With`, there would in interest in a delegate overload for this reason)

That said, I don't think these couldn't be achieved in other ways using Autofac or with your extension method. If there are concerns about maintainability or bloat, then I'm fine with #794 being closed.

**Comment by abatishchev** [comment] 2017-08-17 15:41
I believe these are quite common and realistic scenarios actually:

- You generate dummy data, send it to a database, database has constraints (column sizes, foreign keys, etc.)
- You generate dummy data, send it to a web service, web service has constraints (field length validation)

What is uncommon and unrealistic is passing back and forth unbound data. Data always has some constraints.

From my perspective, AutoFixture is perfect to generate absolutely random data. But isn't that good to make this generation controllable, extensible.

Having two two overloads accepting a constant or a delegate is a very common design approach, isn't it?

**Comment by zvirja** [comment] 2017-08-17 18:39
Thank you guys for sharing your scenario. 

Personally, I'm fine adding this feature as soon as we manage the concerns mentioned [here](https://github.com/AutoFixture/AutoFixture/pull/794#issuecomment-321228263)
and [here](https://github.com/AutoFixture/AutoFixture/pull/794#issuecomment-321259319). Technically it's very easy to implement this and support of this feature shouldn't cost too much. On more `With` method overload looks organic to me. 

However, I'd like to delegate the decision making to @moodmosaic as he worked longer on this project and has better vision regarding such things.

**Comment by moodmosaic** [comment] 2017-08-19 11:22
While the proposed solution has real-world usage(s), is it *common*?

* How about using the method provided by @zvirja [here](https://github.com/AutoFixture/AutoFixture/issues/708#issuecomment-321508595)?
* The current API around `.Build` is all about [*explicit is better than implicit*](https://www.python.org/dev/peps/pep-0020/).

In addition to that, the [provided sample](https://github.com/AutoFixture/AutoFixture/issues/708#issue-179038084) shows a test which is difficult to write―with or without the proposed overload, the [Fixture Setup](http://xunitpatterns.com/fixture%20setup.html) phase is a bit involved.
* In the spirit of [GOOS](https://www.amazon.com/Growing-Object-Oriented-Software-Guided-Tests/dp/0321503627), if the test is difficult to write, it's probably because the API is difficult to use...

**Comment by abatishchev** [comment] 2017-08-19 15:52
I frankly don't get why you've this and that. Neither I buy the reasons for it. A *bit*? Did you mean *heavily*? My tests dataprep step involves setup *heavily*. And it's messy. And you leave me with this mess, refusing add an organic overload to accept Fun<T> alongside with T. Nothing less explicit here. I just continue having tests that are harder to write, read, and maintain. Because the API is harder to use. And you refused to make it simpler.

**Comment by Kralizek** [comment] 2017-08-20 06:40
I guess what we all fail to see is that AutoFixture is not only used for unit testing. 

For example, I plan to use it to generate dummy data to fill in a part of the system that usually contains sensible information that most developers cannot be exposed to. I didn't really work on that part of the system yet, but from what I read a "generator" would be helpful.

just my 2c

**Comment by zvirja** [comment] 2017-08-21 09:57
@moodmosaic Could you please elaborate? 😉

**Comment by moodmosaic** [comment] 2017-08-29 02:28
This pull request, while interesting to me, addresses a scenario which I'm not convinced is common enough so that it may be include, and maintained (as per [Semantic Versionin 2.0.0](http://semver.org/)), in the codebase.

@abatishchev, I don't think you're left with any mess; AutoFixture supports customizations and extensions, so you can add your own ad-hoc extension method(s) or glue librarie(s) to it.

**Comment by zvirja** [comment] 2018-03-08 10:27
Decided to give it a shot in #990.

**Comment by ploeh** [comment] 2018-03-08 11:25
I came here via https://stackoverflow.com/a/49167084/126014, so I may misinterpret what's going to happen here, but I'm not convinced that adding an overload to `With` where you supply a lazily evaluated delegate is warranted.

Please don't take this feedback as more than it is, but whenever you add a feature to any code base, there's always the consideration that the benefits must outweigh the disadvantages.

Writing open source code is fundamentally different than writing commercial software. When you write commercial software, or enterprise software for that matter, you're being paid to write the code, but usually, someone else makes the final call on which features should be in the software. You may discuss this with the product owner, but ultimately, it's their decision if they think a feature is worth the extra maintenance burden.

When you write open source software, (typically) no-one pays you, but the maintenance burden is still yours. This should make you more conservative when adding new features, because the cost is real, but the benefit is much more nebulous.

Concretely, I don't remember whether or not this proposed feature is easy to add or maintain, so don't put more into what I wrote than that.

I do agree with @moodmosaic, though, that as maintainers, you get to decide what you want to maintain. I think the only way you can make such decisions is if you have a clear _vision_ for the software. Such a vision enables you to always ask the question:

> Does this proposed feature look like it gets us nearer the vision?

If the answer is _yes_, then you approve of the feature in principle. If the answer is _no_, you reject the idea.

My original vision for AutoFixture was as a TDD tool. While I had that vision, I was fully aware that other people was using AutoFixture differently, and that made me happy, but didn't mean that I'd uncritically add any feature people requested.

I also stepped down as a maintainer of AutoFixture because I no longer had any vision for it. As far as I was concerned, the job was _done_.

Thus, it's perfectly fine if you've adopted a different vision for AutoFixture going forward, but if you have, I don't know what is is. Under the original vision, however, I would be _extremely_ conservative about adding this new feature.

It's not that I oppose it in principle; I don't. It's only that, like @moodmosaic writes, the only rationale I've ever seen for this feature had their root causes in design issues with the code being tested. With such motivations, my tolerance for additional maintenance burden would have been close to non-existing.

Still, I don't know how difficult this feature will be to maintain, and I also don't know what the new vision for AutoFixture is, so I only offer this little essay as food for thought 😄

**Comment by moodmosaic** [comment] 2018-03-08 17:38
👍 on what @ploeh wrote.

**Comment by zvirja** [comment] 2018-03-08 21:11
Hi Mark. Thanks for spending your time and raising this important note. I believe that I clearly see your message and moreover, I completely agree with it. It's pretty obvious that OSS project is not being paid and we spend our free time making it better and maintaining it. Therefore, we definitely are not forced to (and should not) accept any new feature people ask us about if we don't see why it's needed or if it doesn't comply with our vision. Without following this rule the project might quickly become a mess and we will spend more and more time to support it. If that was what you tried to warn me about - I got it 😉

However, there is another side of my vision. AutoFixture is a great tool _to simplify_ test writing and it has its API. We should keep that API as small as possible, but in the same time provide flexibility in the supported user scenarios. There are some fundamental features we explicitly don't want to support (e.g. assignment of the private members), but for the rest - we should be fine in providing a way to achieve them. AutoFixture product is not ideal and sometimes you should fight against it to achieve the desired result. When I see a new API that could enable a bunch of real scenarios which don't fall into "explicitly non-supported" category, I'm very happy to add that API. I'm excited that it's yet another fundamental brick which makes the library even more awesome and suitable. Of course, I evaluate whether the existing usage scenarios are not affected and whether the API doesn't become overwhelmed/inconsistent now. If everything is fine with that - I don't see any other reason to decline. I am not afraid of the slightly increased support costs unless it really requires huge investments. After all, development is not dead and we shouldn't freeze the further product improvements if there is a need. It's totally fine to me that some features with add more lines to the AutoFixture - code is covered by the tests and such changes are necessary to evolve.

The change suggested by this issue is reasonable to me and I've already met scenarios when it might be handy. That's especially valuable when you use the `Customize()` method to make a global customization and you don't want your customized objects to share the same injected value. To me the `.Without(x => x.Property).Do(x => x.Property = GenerateValue())` chain is a [kludge](https://en.wikipedia.org/wiki/Kludge) around the limitations of the API, rather than a feature we explicitly want to provide. The change to add the `With(..)` method overload taking a delegate will organically extend the existing API without making it brittle. It's a well known contract for all the developer to pass a delegate when you would like to generate a unique value per call, rather than a constant. 

As for the maintenance costs - it's negligible, as all the underlying infrastructure is already using the delegate, and actually under the hood [we construct a delegate from the constant](https://github.com/AutoFixture/AutoFixture/blob/9121cedad8b8eddc8993552ba87a06fbc92f97be/Src/AutoFixture/Kernel/BindingCommand.cs#L54).

I don't want to see AutoFixture as a zombie project which is not ready to support a new generic feature simply because it's afraid that somebody needs to support that code. Of course, we need to evaluate the feature/size ratio and ensure that it worth it, however if value is not very crazy - we must be fine. In this respect I like the NSubstitute library principles:
* NSub aims to make the common use cases simple and easy. We want to make more advanced stuff possible, but not compromise the main use cases.
* New features should have a realistic, motivating example (we try to avoid guessing what things will be useful).

----

Therefore, answering to this question
> Does this proposed feature look like it gets us nearer the vision?

For me the answer is yes. This feature enables the realistic scenarios, provides a good extensibility opportunities, is quite generic, is intuitive in usage, makes no impact on the current usage, makes the API more complete and is very cheap in the maintenance.

Thanks again for raising the question and forcing me to re-evaluate the decision - I highly appreciate that! 🙇 Hope my answer shed some light on the reasons behind my decision and you can see that it makes sense 😅 As you can see, I still respect the principles you followed and fully agree with them - the main point is that I probably see more value from the suggested change than you and for me this feature doesn't contradict with the philosophy/aims of the project 😉

**Comment by Kralizek** [comment] 2018-10-14 07:55
Just to clarify, the options were all variations of the With method that accept, after the lambda expression used to specify the property to customize,

* A lambda with no parameters, the user will capture the external fixture 
* A lambda with a fixture as parameter, the user can cleanly create/use external functions as they don't need any captured context
* A lambda with a number of parameters ranging from 0 to N, each parameter will be created and passed to the function.

I would personally prefer the second option. To investigate if introducing the third one can create friction.

The first one is simply a dirtier version of the second, so I'd keep it away.

**Comment by zvirja** [comment] 2018-10-15 21:55
Hi @Kralizek,

Please take my apologize for the delayed replay 😖 

I believe that we should add the following overloads to the `IPostprocessComposer<T>` interface:

```c#
IPostprocessComposer<T> With<TProperty>(Expression<Func<T, TProperty>> propertyPicker, Func<TProperty> valueFactory);
IPostprocessComposer<T> With<TProperty, TInput>(Expression<Func<T, TProperty>> propertyPicker, Func<TInput, TProperty> valueFactory);
```

That will provide you with a freedom to take any argument you wish, but also don't consume any if you don't need that:
```c#
fixture.Build<TypeWithProperty>()
    .With(x => x.Value, () => "blah")
    .Create();

fixture.Build<TypeWithProperty>()
    .With(x => x.Value, (int value) => value.ToString())
    .Create();

fixture.Build<TypeWithProperty>()
    .With(x => x.Value, (IFixture f) => f.Create<byte>().ToString())
    .Create();
```

> A lambda with a number of parameters ranging from 0 to N, each parameter will be created and passed to the function.

These ones might be later implemented as extension methods and under the hood use the implementation taking a single arg of `IFixture` type.

Would be super awesome if you could find some free time and implement this via PR 🍺 I'm very busy today and unfortunately am not sure when I can put my hands on that in the nearby future.

**Comment by Kralizek** [comment] 2018-10-16 14:10
@zvirja I was trying to assign this issue to myself but I can't. Can you do it for me? :)

**Comment by zvirja** [comment] 2018-10-16 17:15
I cannot do that neither - it's allowed to assign the project members only :confused: But don't afraid - the activity in this project is quite low these days, so it's unlikely to get race conditions :sweat_smile:

**Comment by Kralizek** [comment] 2018-10-17 06:30
Wanna have a chat before I start? I got a few questions/ideas I'd like to run through you.

**Comment by ploeh** [comment] 2018-10-17 06:38
> I cannot do that neither - it's allowed to assign the project members only

Are you not a project member? I thought that I transferred all rights to you. Is there anything I can do to improve the situation?

**Comment by zvirja** [comment] 2018-10-17 08:14
> Wanna have a chat before I start? I got a few questions/ideas I'd like to run through you.

Well, as long as they don't change the public API shape, I leave it up to you to find the internal approach to do this. However, if you prefer to discuss something beforehand - I don't mind 😉 

> Are you not a project member? I thought that I transferred all rights to you. Is there anything I can do to improve the situation?

@ploeh Thanks Mark for your readiness to help! 😊 You slightly misunderstood me - I have enough rights to assign people, I simply cannot pick non-project members in the dropdown. It's unlikely you can improve that unless you have direct contacts of GitHub team members 😅

**Comment by ploeh** [comment] 2018-10-17 08:16
>  I simply cannot pick non-project members in the dropdown.

Oh, right, yes that's right. That's just how GitHub works. I forgot that.

**Comment by Kralizek** [comment] 2018-10-17 13:18
> Well, as long as they don't change the public API shape, I leave it up to you to find the internal approach to do this. However, if you prefer to discuss something beforehand - I don't mind 

It's not about the public API but testing strategies and about [your comment](https://github.com/AutoFixture/AutoFixture/issues/708#issuecomment-430028361)

**Closed** 2018-12-10 08:36 UTC
Labels: enhancement, good first issue
