### ISSUE TITLE
Idioms: ConstructorInitializedMemberAssertion returns false positive in case of bool types

### ISSUE THREAD

**Issue by WarBorg** [AutoFixture/AutoFixture#1235] opened 2021-02-20 16:57 UTC
hello,

I have studied the issues related to ConstructorInitializedMemberAssertion on this repo and I think I found another bug:

given:
```c#
public class MyClass
    {
        public SomeEnum SomeEnumValue { get; }
        public bool IsSomeBool { get; }

        public MyClass(SomeEnum someEnumValue, bool isSomeBool)
        {
            SomeEnumValue = someEnumValue;
        }
    }
```
with the test:

```c#
        private IFixture _fixture;

        [SetUp]
        public void SetUp()
        {
            _fixture = new Fixture();
        }

        [Test]
        public void ReadonlyPropertiesShouldHaveConstructorParameterAssignedValues()
        {
            // Arrange
            var guardClauseAssertion = new ConstructorInitializedMemberAssertion(_fixture);

            var someEnumValueMember = typeof(MyClass).GetProperty(nameof(MyClass.QuickActionItemType));
            var isSomeBoolMember = typeof(MyClass).GetProperty(nameof(MyClass.IsTurnedOn));

            // Act / Assert
            guardClauseAssertion.Verify(typeof(MyClass));
            guardClauseAssertion.Verify(someEnumValueMember);
            guardClauseAssertion.Verify(isSomeBoolMember);
        }
```
the test passes but I would expect it to fail,

when debugging I observed that in both constructor verification call and members verification calls, 
* the first time the constructor is called the enum parameter value is set to "non first value" and the bool parameter is set to true, but only the enum type property is checked
* the second time the constructor is called the enum parameter value is again set to "non first value" but the bool parameter is now set to false and the bool property value is checked, since that default bool value is false then the test will pass 

if I switch the last to statements from the unit test and put the bool check first:

```c#
guardClauseAssertion.Verify(isSomeBoolMember);
guardClauseAssertion.Verify(someEnumValueMember);
```

then everything works as expected and the test fails, but I don't think you should care about the order of the statements

**Comment by aivascu** [comment] 2021-02-20 21:59
@WarBorg I had a brief look at the assertion implementation. It seems the issue is caused by the assertion resolving the values for all constructor parameters whenever it tries to assert if a single member was properly initialized.
Since the values for the `bool` type are generated in a round robin fashion, and the `bool` argument is second in the list of parameters. This means that whenever the `bool` parameter will be validated, it will be asserted against `false`, which happens to be the default value for the `bool` type.

There is already a [workaround](https://github.com/AutoFixture/AutoFixture/blob/c56d708b1ef3d03be313848c11d5a52855b54e09/Src/Idioms/ConstructorInitializedMemberAssertion.cs#L276) that prevents this issue from happening to the `enum` values. This workaround forces the target value to be regenerated whenever it matches the default value. I imagine the same fix could apply to boolean values.

The other solution I see, that would reliably verify the properties/fields received the expected values, is to do the assertion in two consecutive passes. One of the passes would inevitably, assert against an alternating set of values to those set in the constructor.

**Comment by WarBorg** [comment] 2021-02-21 13:26
@aivascu awesome, one question, since I am not really that familiar with AutoFixture internal workings, does your fix also take into consideration the possibility that the user sets the boolean property to have the initial value of `true` ?

**Comment by aivascu** [comment] 2021-02-21 14:07
@WarBorg no, and neither does the assertion take into consideration any other default values set before the construction of the object. The assumption AFAIKT is that the constructor will provide all the necessary data for the instance to be constructed in a valid state. If your implementation does not comply with this rule, then you might want to manually the test.

It might be worth having an attempt at running the assertion in multiple iterations to see if the members change overtime with the input parameters, but that's likely going to be a different assertion.

**Closed** 2021-03-08 07:14 UTC
Labels: bug
