### ISSUE TITLE
GuardClauseAssertion - Optional parameters 

### ISSUE THREAD

**Issue by tklingert** [AutoFixture/AutoFixture#442] opened 2015-09-23 14:49 UTC
Hi,

in general, the GuardClauseAssertion works fine and saves a lot of repetitive work.
Thumbs up :)

Sadly optional parameters are verified too, hence result in a failure:
```csharp
    myCtor( string optionalValue = null )
```
First i thought an easy workaround would be to use a customized NullReferenceBehaviorExpectation instead, but the parameter information which is needed to distinguish between optional and non-optional parameters is not available in this context.

Wouldn't it be reasonable if "GuardClauseAssertion.GetParameters(IMethod method)" ignores optional parameters ?
e.g. via ParameterInfo.IsOptional or ParameterInfo.HasDefaultValue

Kind regards,

Thorsten

**Comment by ploeh** [comment] 2015-09-23 15:44
Thank you for writing.

This issue is, I think, a duplicate of #286, so I'm going to close it here.

**Closed by ploeh** 2015-09-23 15:44 UTC
