### ISSUE TITLE
Generator spins infinitely

### ISSUE THREAD

**Issue by jiimaho** [AutoFixture/AutoFixture#732] opened 2017-02-07 15:05 UTC
When you pick a number of distinct values from a generator that exceeds the total possible number of values for the type itself, the generator spins inifintely.

The following code will never reach the third line.

            var foo= new Generator<byte>(Fixture).Distinct().Take(100).ToList(); // ok
            var bar= new Generator<byte>(Fixture).Distinct().Take(2000).ToList(); // spins
            var bass= new Generator<byte>(Fixture).Distinct().Take(2000).ToList(); // never reached

Running version 3.49 of AutoFixture

**Comment by sergeyshushlyapin** [comment] 2017-02-07 20:14
IMO that's expected behavior. How could you get more _unique_ values than the maximum possible number of values for the given type?

The `Generator` class [Generates a _perpetual_ sequence of items](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Generator.cs#L9) (there is [endless loop](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Generator.cs#L49) in the `GetEnumerator` method). Why don't you _take_ bytes first and then apply the `Distinct` filter? Of course, you won't get more than 256 `byte` instances.

BTW, the fixture can be customized with the `ByteSequenceGenerator` to _simplify_ generating the _unique_ bytes: 
 
```csharp
      var fixture = new Fixture();
      fixture.Customizations.Insert(0, new ByteSequenceGenerator());

      var foo = new Generator<byte>(fixture).Take(100).Distinct().ToList();
      var bar = new Generator<byte>(fixture).Take(2000).Distinct().ToList();
      var bass = new Generator<byte>(fixture).Take(2000).Distinct().ToList();

      foo.ForEach(x => Console.Out.WriteLine("foo = {0}", x));
```
```
*** ConsoleOutput ***

foo = 1
foo = 2
foo = 3
foo = 4
foo = 5
...
foo = 99
foo = 100
```

**Comment by jiimaho** [comment] 2017-02-08 11:55
> IMO that's expected behavior. How could you get more unique values than the maximum possible number of values for the given type?

Of course you can't, thats not my point. I was just thinking that throwing an exception rather then looping endless i'd be a better choice.

**Comment by zvirja** [comment] 2017-07-09 20:48
> I was just thinking that throwing an exception

@jiimaho It isn't obvious which exact exception might be thrown here and what should be a condition for that.. I wouldn't add a hard threshold like 1,000,000 of items generated, because sometimes it might be needed. Do you have any particular idea in mind how AF could do something over this?

Thanks 😉

**Comment by zvirja** [comment] 2017-08-18 09:52
I'm closing this issue as it doesn't seem we could help with it somehow. If you see a way to improve AutoFixture implementation in this area, please feel free to re-open the issue.

**Closed by zvirja** 2017-08-18 09:52 UTC
Labels: question
