### ISSUE TITLE
Mixing AutoFixture attributes with NUnit3 ones

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#997] opened 2018-03-10 10:22 UTC
Hi,

This is more of a question than an actual issue, so please take it as it is.

I was trying to write a unit test that should assert the behavior of my system under a certain range of conditions.

The test takes in 5 variables, for the first two I want to provide a set of values, the last three can be autogenerated by AutoFixture.

For the first case, NUnit supports attributes like [`ValuesAttribute`](https://github.com/nunit/docs/wiki/Values-Attribute). Ideally, together with `InlineAutoData` should generate all the combination of tests I was looking for.

Here is some code

This works but its suboptimal
```csharp
[Test]
[InlineAutoData("GET", HttpStatusCode.NotFound)]
[InlineAutoData("POST", HttpStatusCode.NotFound)]
[InlineAutoData("PUT", HttpStatusCode.NotFound)]
[InlineAutoData("DELETE", HttpStatusCode.NotFound)]
public void SendAsync_throws_HttpException_if_nonSuccessful_response(string method, HttpStatusCode statusCode, Uri uri, Request request, Response response)
{
    var httpMethod = new HttpMethod(method);

    var options = new[]
    {
        new HttpMessageOptions
        {
            RequestUri = uri,
            HttpMethod = httpMethod,
            HttpContent = new StringContent(JsonConvert.SerializeObject(request, serializerSettings)),
            HttpResponseMessage = new HttpResponseMessage(statusCode)
            {
                Content = new StringContent(JsonConvert.SerializeObject(response, serializerSettings))
            }
        }
    };

    var sut = CreateSystemUnderTest(options);

    Assert.ThrowsAsync<HttpException>(() => sut.SendAsync<Request, Response>(httpMethod, uri.ToString(), request));
}
```

What I would have liked to do is

```csharp
[Test]
[AutoData] // or [InlineAutoData]
public void SendAsync_throws_HttpException_if_nonSuccessful_response(
    [Values("GET", "POST", "PUT", "DELETE")] string method, 
    [Values(HttpStatusCode.NotFound, HttpStatusCode.Unauthorized, HttpStatusCode.ServiceUnavailable)] HttpStatusCode statusCode, 
    Uri uri, Request request, Response response)
{
    var httpMethod = new HttpMethod(method);

    var options = new[]
    {
        new HttpMessageOptions
        {
            RequestUri = uri,
            HttpMethod = httpMethod,
            HttpContent = new StringContent(JsonConvert.SerializeObject(request, serializerSettings)),
            HttpResponseMessage = new HttpResponseMessage(statusCode)
            {
                Content = new StringContent(JsonConvert.SerializeObject(response, serializerSettings))
            }
        }
    };

    var sut = CreateSystemUnderTest(options);

    Assert.ThrowsAsync<HttpException>(() => sut.SendAsync<Request, Response>(httpMethod, uri.ToString(), request));
}
```

Ideally this should give 12 tests, instead of only 1.

**Comment by zvirja** [comment] 2018-03-10 11:36
Is it a duplicate of #343?

**Comment by Kralizek** [comment] 2018-03-10 11:42
Oops yes, my bad for not looking with more care at the open issues...

**Comment by zvirja** [comment] 2018-03-10 17:18
Duplicate of #343

**Closed by zvirja** 2018-03-10 17:18 UTC
