### ISSUE TITLE
Create object with guid field with validation attribute "RegularExpression" throws 'AutoFixture.ObjectCreationExceptionWithPath'

### ISSUE THREAD

**Issue by ttlaare** [AutoFixture/AutoFixture#1172] opened 2020-03-30 18:25 UTC
![image](https://user-images.githubusercontent.com/47394927/77943744-061ae500-72be-11ea-947a-0c8136afe557.png)

Creating an object using texture with a guid field with a validation attribute "RegularExpression" throws 'AutoFixture.ObjectCreationExceptionWithPath'. 

Using a builder will not throw an exception, so I will use that as a work around.

**Comment by Ergamon** [comment] 2020-04-18 20:45
As noone replies, I try my best ;)

You may argue that the problem is in AutoFixture. Personally I would see it more in your code.

The RegularExpressionAttribute is meant for strings. So your expression defines how a Guid should look as a string.
If AutoFixture finds this attribute it automatically creates a string matching the pattern. (This is where it gets debatable. AutoFixture could (or should?) check if the type is really a string)
But your property type is Guid. The coder of AutoFixture did not expect this and to be fair, it does not make any sense.

**Comment by ecampidoglio** [comment] 2020-04-20 09:49
@Ergamon There's nothing preventing you from applying the `RegularExpressionAttribute` on a property of type `object`. In fact, the [example in the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.regularexpressionattribute?view=netframework-4.8#examples) does just that:

```csharp
public class CustomerMetaData
{
    // Allow up to 40 uppercase and lowercase 
    // characters. Use custom error.
    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", 
         ErrorMessage = "Characters are not allowed.")]
    public object FirstName;

    // Allow up to 40 uppercase and lowercase 
    // characters. Use standard error.
    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$")]
    public object LastName;
}
```

Regardless of what you think of this design choice, AutoFixture cannot enforce the rule that `RegularExpressionAttribute` should only be applied on `string` properties, since the BCL itself doesn't do that.

@ttlaare I understand the need to validate that the `Guid` property isn't set to an empty GUID. However, the type of the property and the `RegularExpressionAttribute` are sending mixed signals to AutoFixture: on one hand you're saying that you want a `Guid`, but on the other you're also saying that it should be treated as a `string`.
This is a classic case where you need to _teach_ AutoFixture how to create valid test data for you, since it can't _infer_ it just by looking at your object model. Creating a custom builder, as you suggested, is a perfectly good solution.

I'm going to close this issue as *by design*. Feel free to reopen, if you'd like to discuss this further.

**Closed by ecampidoglio** 2020-04-20 09:49 UTC

**Comment by ttlaare** [comment] 2020-04-20 09:58
Hi @Ergamon and @ecampidoglio,

After reading your comments I agree that RegularExpressionAttribute should only be applied on string properties, so I will keep this issue closed. 

I will create a custom validation attribute that returns falls when a Guid has a default value, instead of using the RegularExpressionAttribute. 

Thanks for the support!
