### ISSUE TITLE
Getting NSubstitute CouldNotSetReturnDueToTypeMismatchException after upgrading to 4.0.1

### ISSUE THREAD

**Issue by sam-piper** [AutoFixture/AutoFixture#975] opened 2018-02-01 00:45 UTC
I just upgraded to these packages in our xUnit .NET Core 2 Unit Test project:

* AutoFixture 4.0.1  (from 3.51)
* AutoFixture.AutoNSubstitute 4.0.1 (from 3.51)
* AutoFixture.Xunit2 4.0.1 (from 3.51)
 
And now there are 30+ tests all failing that look like this:

```
NSubstitute.Exceptions.CouldNotSetReturnDueToTypeMismatchException : Can not return value of type Member for Entity.OnObjectStateChanged (expected type Void).

Make sure you called Returns() after calling your substitute (for example: mySub.SomeMethod().Returns(value)),
and that you are not configuring other substitutes within Returns() (for example, avoid this: mySub.SomeMethod().Returns(ConfigOtherSub())).

If you substituted for a class rather than an interface, check that the call to your substitute was on a virtual/abstract member.
Return values cannot be configured for non-virtual/non-abstract members.

   at NSubstitute.Core.ConfigureCall.CheckResultIsCompatibleWithCall(IReturn valueToReturn, ICallSpecification spec)
   at NSubstitute.Core.ConfigureCall.SetResultForLastCall(IReturn valueToReturn, MatchArgs matchArgs)
   at NSubstitute.Core.SubstitutionContext.LastCallShouldReturn(IReturn value, MatchArgs matchArgs)
   at AutoNSubstitute.Bugs.AccountServiceTest.GetAccountItems() in C:\Source\AutoNSubstitute.Bugs\AutoNSubstitute.Bugs\AccountServiceTest.cs:line 64
```

STEPS TO REPRODUCE:

1. Create a new xUnit .NET Core 2 project in Visual Studio 2017 (currently 15.5.2)
2. Add AutoFixture packages as indicated above
3. Add NSubstitute 3.1.0 package
4. Copy and paste this code into a source file:

```c#
using System;
using AutoFixture;
using AutoFixture.AutoNSubstitute;
using NSubstitute;
using Xunit;

namespace AutoNSubstitute.Bugs
{
    public enum ObjectState
    {
        Unchanged = 0,
        Added = 1,
        Modified = 2,
        Deleted = 3
    }

    public abstract class Entity
    {
        private ObjectState _objectState = ObjectState.Added;

        public Guid Id { get; set; }

        public ObjectState ObjectState
        {
            get => _objectState;
            set
            {
                if (_objectState != value)
                {
                    _objectState = value;
                    OnObjectStateChanged();
                }
            }
        }

        protected virtual void OnObjectStateChanged()
        {
        }
    }

    public abstract class BusinessEntity : Entity
    {
    }

    public class Member : BusinessEntity
    {
    }

    public interface IBusinessEntityService
    {
        BusinessEntity GetBusinessEntity(Guid id, bool clone);
    }

    public class AccountServiceTest
    {
        [Fact]
        public void GetAccountItems()
        {
            var member = new Member();
            var fixture = new Fixture().Customize(new AutoConfiguredNSubstituteCustomization());
            var businessEntityService = fixture.Freeze<IBusinessEntityService>();

            // throws error!
            businessEntityService.GetBusinessEntity(member.Id, false).Returns(member);
        }
    }
}
```

It looks like AutoFixture is accidentally cycling into the `member` variable when setting up the expectation on the `businessEntityService` interface substitute, and trying to treat it as a fixture as well - when I debug the line that throws the error, it is setting the ObjectState property on `member` to a new value, which didn't happen in the previous versions of AutoFixture with NSubstitute integration, and this is triggering a problem in NSubstitute.

Can someone please investigate this issue and advise of when this might get fixed?

**Comment by zvirja** [comment] 2018-02-02 13:52
@sam-piper Thanks for reporting the issue and for providing me with the detailed scenario - that helped a lot! I was able to reproduce it locally and now I'm trying to figure out the best way to fix it - it's not that easy 😟 

This bug has been introduced in v4 after I've reworked the integration approach. We didn't have such a scenario in our tests, so I haven't captured it earlier.

I'll update the ticket after I finish the investigation.

**Comment by zvirja** [comment] 2018-02-02 16:05
@sam-piper So far I wasn't able to find a good way to mitigate the issue. Therefore, as a workaround I'd suggest to modify your code as following:
```c#
// Before:
// businessEntityService.GetBusinessEntity(member.Id, false).Returns(member);
// After
businessEntityService.GetBusinessEntity(Arg.Is(member.Id), false).Returns(member);
```

That will prevent AutoFixture integration from activation and the returned value will be configured properly. While that is a workaround, it isn't that ugly as you use the [`Arg.Is()`](http://nsubstitute.github.io/help/argument-matchers/) extension by design.

Let me know whether it works fine for you!

In the meanwhile I'll try to see whether there are other ways to fix the issue, but it's very unlikely that I'll find them.

**Comment by sam-piper** [comment] 2018-02-06 06:07
Thanks for confirming - happy to use Arg.Is() as a workaround as it only affects a small portion of our codebase.

**Comment by zvirja** [comment] 2018-03-05 12:34
Recently [I've contributed](https://github.com/nsubstitute/NSubstitute/pull/352) the `Configure()` extension method to the NSubstitute (will be released in v4). It allows to provide NSubstitute with a hint that the subsequent method invocation will be configured. As a side effect, the AutoFixture becomes disabled for that call, so you can work around the issues you have.

In your case, you can write like following:
```c#
businessEntityService.Configure().GetBusinessEntity(member.Id, false).Returns(member);
```

I'm closing this issue as the `Configure()` extension method is an official way to work around any corner edges we might have. It's impossible to fix this issue reliably in some other way, as scenario is very cross-cutting and involves a large number of different subsystem.s

Let me know if you find that `Configure()` method is not enough for you.

Thanks again for raising the issue! 👍

**Closed by zvirja** 2018-03-05 12:34 UTC
Labels: bug
