### ISSUE TITLE
Change build server to use the new FAKE-based build scripts

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#551] opened 2016-03-13 15:41 UTC
With #523 we got a new build script for AutoFixture. Instead of `build-release.sh`, I'm now using `build.sh` to build and publish a new version of AutoFixture, So far, I've released 3.40.1, 3.41.0, and 3.41.1 with this script.

Because of changes made to the `.nuspec` files, the old `build-release.sh` script fails at the create-NuGet-packages step. This means that all recent pull request verification builds (since #523 was merged) have been failing.

We need to change the build servers so that they use the new build scripts. @ecampidoglio, will you either make the change, or share with me credentials so that I can make that change?

**Comment by ecampidoglio** [comment] 2016-03-13 20:13
I updated the [build](https://ci.appveyor.com/project/AutoFixture/autofixture) on AppVeyor to use the [new build script](https://github.com/AutoFixture/AutoFixture/blob/master/Build.fsx) and everything seems to work nicely.

However, we do have one minor issue: the NUnit tests aren't being published in the build results, only the xUnit ones do. The problem is twofold:

1. The build script [deletes](https://github.com/AutoFixture/AutoFixture/blob/master/Build.fsx#L159) the `TestResult.xml` file _before_ AppVeyor gets a chance to publish the results.
2. The NUnit2 and NUnit3 console runners send their results to the same `TestResult.xml` file — this means that whichever is run last (in this case NUnit3) is going to overwrite the results from the previous one.

If we want _all_ tests to be published — and I certainly think we should — then we need to do two minor modifications to the build script:

1. Add a target that does a complete build but doesn't delete the test result files.
2. Pass the `/result:NUnit2TestResult.xml` option to the NUnit2 console runner and `--result:NUnit3TestResult.xml;format=nunit2` to the NUnit3 one (as per the [documentation](https://github.com/nunit/docs/wiki/Console-Command-Line#description)) to save the results in two different files.

I can make these modifications myself but I thought that maybe @ErikSchierboom or @hackle want to take a shot at it, since they've been working on the new build script.

What do you think?

**Comment by ecampidoglio** [comment] 2016-03-13 20:19
Also, I should mention that the members of the AutoFixture [core team](https://github.com/orgs/AutoFixture/teams/core) are already administrators in the [AutoFixture project](https://ci.appveyor.com/project/AutoFixture/autofixture) on AppVeyor. You can simply login with your GitHub account and you'll be able to modify any aspect of the build process.

**Comment by ploeh** [comment] 2016-03-13 20:48
(I didn't know that we had administrator rights, but thanks for doing this.)

Should we close this issue, and create a new one?

**Comment by ErikSchierboom** [comment] 2016-03-13 22:14
I'd be happy to look at this tomorrow. Maybe what we want is the build to not delete the test result files, but add them to the `.gitignore` file to prevent them from being committed?

**Comment by ploeh** [comment] 2016-03-14 06:26
That's what I thought, too, when I read the original problem description :smile:

**Comment by ErikSchierboom** [comment] 2016-03-14 08:37
@ecampidoglio I have submitted PR #563, which has the NUnit runners write to separate test result files and outputs the NUnit 3 results in NUnit 2 format. Could you check if it works on AppVeyor?

By the way, the [AppVeyor docs](https://www.appveyor.com/docs/running-tests#nunit-3-x) suggest that the nunit3-console should be run with the `format=AppVeyor` instead of `format=nunit2` argument, however, that broke my local build so I used the NUnit 2 argument you suggested.

**Comment by ecampidoglio** [comment] 2016-03-14 09:19
Resolved by #563.

**Closed by ecampidoglio** 2016-03-14 09:19 UTC
Labels: bug
