### ISSUE TITLE
Comparing nested list fails while comparing list alone works.

### ISSUE THREAD

**Issue by JoshMcCullough** [AutoFixture/AutoFixture#585] opened 2016-03-18 15:41 UTC
When a likeness's value contains a nested list, `ShouldEqual` fails. But when I compare the exact lists themselves, it succeeds. Here are the test cases:

- NestedList_Works >> Fails
- List_Works >> Succeeds

```
namespace Test
{
    [TestClass]
    public class SemanticComparisonTests
    {
        [TestMethod]
        public void NestedList_Works()
        {
            var user = new User();
            var likeness = user.AsSource().OfLikeness<User>();
            var otherUser = new User();

            likeness.ShouldEqual(otherUser);
        }

        [TestMethod]
        public void List_Works()
        {
            var user = new User();
            var likeness = user.Roles.AsSource().OfLikeness<List<string>>();
            var otherUser = new User();

            likeness.ShouldEqual(otherUser.Roles);
        }

        class User
        {
            public string Username { get; set; } = "big_jim_6";
            public List<string> Roles { get; set; } = new List<string>()
            {
                "User",
                "PowerUser",
                "ClientAdmin"
            };
        }
    }
}
```

**Comment by ploeh** [comment] 2016-03-18 17:11
This is because `List<T>` has _reference equality_ (as opposed to _structural equality_), which means that instances are only considered equal if they point to the same address in memory.

As #48 explains, `Likeness` doesn't do recursive structural comparison at the moment (and I honestly doubt that it ever will).

Since I consider that this issue is essentially a duplicate of #48, I'm going to close this one. If you disagree, please let me know. I can always reopen the issue if you think that this is a different issue.

**Closed by ploeh** 2016-03-18 17:11 UTC

**Comment by JoshMcCullough** [comment] 2016-03-18 18:34
Yes, this is precisely #48. Sorry, I thought `Likeness` handled deep comparisons. Thanks!

**Comment by ploeh** [comment] 2016-03-18 21:32
That's OK. 24 open issues (and all the closed ones) is already too many :flushed:, so I don't expect anyone else to be able to see through all of that.
