### ISSUE TITLE
Change ModestConstructorQuery behavior to skip copy constructors

### ISSUE THREAD

**Issue by desmondgc** [AutoFixture/AutoFixture#918] opened 2017-11-07 18:47 UTC
I feel like an improvement similar to the one made in #644 should also be applied to ModestConstructorQuery - skip constructors that contain parameters of the requested type in order to avoid circular references.

**Comment by zvirja** [comment] 2017-11-07 21:15
Hi @desmondgc,

Thanks for registering the issue for us. In order to better understand the context of the issue, could please show a real world samples of the situation when such API is present?

While it's possible to skip those methods, we should make such decisions very carefully. Current AutoFixture's approach is to activate objects when everything is trivial. When there some complications with a design of a particular class, we usually don't attempt to handle all the possible cases out-of-the-box and require user to customize the fixture.

Let's see what are the samples and whether they cover some _common_ real-world scenario.

**Comment by desmondgc** [comment] 2017-11-08 14:15
We want to hide the default public constructor in many of our domain entities in order to force users to call a specific constructor which may include guards and other construction logic. Most of these entities include a copy constructor which also happens to be the "most modest" constructor. In unit tests, we generally want to use AutoFixture default behavior to call the most modest constructor (excluding the copy constructor).

```
public class Payment
{
    private Payment()
    {
    }

    public Payment(Payment payment)
    {
        if (payment == null)
        {
            throw new ArgumentNullException(nameof(payment), $"Cannot copy a null {nameof(Payment)}.");
        }

        PaymentUid = payment.PaymentUid;
        CurrencyInitials = payment.CurrencyInitials;
        CurrencyAmount = payment.CurrencyAmount;
        PaymentAmount = payment.PaymentAmount;
        // ...
    }

    public Payment(string currencyInitials, decimal currencyAmount)
    {
        PaymentUid = Guid.NewGuid();
        CurrencyInitials = currencyInitials;
        CurrencyAmount = currencyAmount;
        PaymentAmount = 0;
        // ...
    }

    public Payment(string currencyInitials, decimal currencyAmount, decimal paymentAmount)
    {
        PaymentUid = Guid.NewGuid();
        CurrencyInitials = currencyInitials;
        CurrencyAmount = currencyAmount;
        PaymentAmount = paymentAmount;
        // ...
    }

    private Guid _paymentUid;
    public Guid PaymentUid
    {
        get
        {
            return _paymentUid;
        }

        set
        {
            if (value == Guid.Empty)
            {
                throw new ArgumentException("Guid.Empty is not a valid identifier.");
            }
            else
            {
                _paymentUid = value;
            }
        }
    }

    public string CurrencyInitials { get; set; }
    public decimal CurrencyAmount { get; set; }
    public decimal PaymentAmount { get; set; }
    // ...
}
```

With the current behavior, this causes an ObjectCreationException: AutoFixture was unable to create an instance of type Ploeh.AutoFixture.Kernel.SeededRequest because the traversed object graph contains a circular reference.

**Comment by zvirja** [comment] 2017-11-08 14:37
Thanks for that sample! As far as I got it, your wish is to skip all the constructors that takes only single argument and it's of the current class type.

Meaning that we **are not going** to skip constructors that take more than one argument:
```c#
public class Payment
{
    public Payment(Payment oldPayment, string currency) { }
}
```

@desmondgc Do you agree on that?

If that is so, I'm basically fine with such a feature request. It looks logical to me and such constructors indeed don't look as good candidates for constructions.

However, what concerns me more, is that currently we have the following queries:

- `ModestConstructorQuery`
- `GreedyConstructorQuery`
- `ArrayFavoringConstructorQuery`
- `EnumerableFavoringConstructorQuery`
- `ListFavoringConstructorQuery`

If we are going to ignore copy constructors, should we skip them for all the queries? Otherwise, it will be inconsistent that constructor might still be still picked if other query type is used. Even if those queries "favor" other constructor overloads, they still could end up with a "copy-constructor" if better candidates are missing.

@moodmosaic Could you please share also your thoughts. For me it looks like an improvement for our heuristic and I can't imagine scenario when this change causes issues.

**Comment by desmondgc** [comment] 2017-11-08 15:02
@zvirja Yes, in my case all of our copy constructors take only a single argument of the current type.

I feel like this request is most important with respect to the ModestConstructorQuery since a single-parameter copy constructor will almost always be chosen by this strategy, but is much less likely for GreedyConstructorQuery. I see that the Array/Enumerable/List-favoring queries fall back to the modest strategy so it might be applicable there, too.

**Comment by zvirja** [comment] 2017-11-08 19:48
@desmondgc Thanks for the confirmation. Let's also see what @moodmosaic thinks about that and later decide what to do.

**Comment by zvirja** [comment] 2017-11-08 22:02
@adamchester Your vote will be also appreciated, given that you were involved into #644 😉

**Comment by moodmosaic** [comment] 2017-11-11 05:08
@zvirja, @desmondgc, I'm not sure I follow; which constructor you'd want AF to call in your example?

If the current [constructor strategies](http://blog.ploeh.dk/2011/04/19/ConstructorstrategiesforAutoFixture/) aren't enough, you can always override them and even supply your own custom ones...

**Comment by zvirja** [comment] 2017-11-13 10:49
> which constructor you'd want AF to call in your example?

Given that you have the following type:

```c#
class Payment
{
  public Payment(Payment payment) { }

  public Payment(string currencyInitials, decimal currencyAmount) { }

  public Payment(string currencyInitials, decimal currencyAmount, decimal paymentAmount) { }
}
```

AutoFixture by default should pick the ` public Payment(string currencyInitials, decimal currencyAmount) { }` constructor instead of the `public Payment(Payment payment) { }` as it currently does. Otherwise, it leads to a recursion and fixture simply fails.

>  you can always override them and even supply your own custom ones...

Yep, you can. However, the issue is about improvements for the AutoFixture constructor selection heuristic. If AutoFixture is always unable to construct instances using the "copy constructors", I don't see any value to pick up those constructors and surely fail. Given that we already applied the same enhancement to the factory methods in #644, it looks that we are fine to care about that.

I like to have a robust behavior by default and if somebody has a tricky scenario, he could always [customize fixture](http://blog.ploeh.dk/2011/04/19/ConstructorstrategiesforAutoFixture/) to pick up the copy constructor instead.

**Comment by moodmosaic** [comment] 2017-11-15 09:03
But you can [force AutoFixture to use the greediest constructors](https://stackoverflow.com/a/12425942).

**Comment by zvirja** [comment] 2017-11-15 09:07
Yep. There is a way to work around the issue and configure fixture in a way that it works. There is no issue with that.

The suggestion is to change the default behavior to make it robust as current strategy will _never_ create specimens - exactly what we did in #644.

**Comment by moodmosaic** [comment] 2017-11-16 08:29
Sounds good 👍 Sorry that it took my so long to figure out what needs to be done 😮

**Comment by zvirja** [comment] 2017-11-17 10:30
Converted that to a feature 😉

**Comment by Loppor** [comment] 2017-11-23 13:09
I opened a pull request for this issue 😄

**Closed** 2017-11-30 18:47 UTC
Labels: enhancement, good first issue
